import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
const dir='src/assets/exercise-art/corrected-masters',out='artifacts/art-corrections';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{const page=await browser.newPage({viewport:{width:1200,height:1200}}),files=(await fs.readdir(dir)).filter(f=>f.endsWith('.svg')).sort();
for(const file of files){let source=(await fs.readFile(`${dir}/${file}`,'utf8')).replace(/ stroke="none"/g,'');await page.setContent(source);const b=await page.locator('svg').evaluate(e=>{const b=e.getBBox();return {x:b.x,y:b.y,width:b.width,height:b.height};});const side=Math.max(b.width,b.height)*1.14;const box=[b.x+b.width/2-side/2,b.y+b.height/2-side/2,side,side].map(v=>Number(v.toFixed(3))).join(' ');source=source.replace(/viewBox="[^"]*"/,`viewBox="${box}"`);assert.match(source,/fill="#1f6b4c"/);assert.doesNotMatch(source,/<image|<filter|stroke=|<text/);await fs.writeFile(`${dir}/${file}`,source);await fs.writeFile(`src/assets/exercise-art/${file}`,source);}
for(const appearance of ['light','dark'])for(let offset=0;offset<files.length;offset+=9){const cards=await Promise.all(files.slice(offset,offset+9).map(async f=>`<article><strong>${f.replace('wg-','').replace('.svg','')}</strong><img src="data:image/svg+xml;base64,${Buffer.from(await fs.readFile(`${dir}/${f}`)).toString('base64')}"><div><img class="thumb" src="data:image/svg+xml;base64,${Buffer.from(await fs.readFile(`${dir}/${f}`)).toString('base64')}"></div></article>`));await page.setContent(`<style>body{margin:16px;background:${appearance==='dark'?'#101512':'#f6f5f2'};color:${appearance==='dark'?'#eee':'#151715'};font:13px Arial;display:grid;grid-template-columns:repeat(3,1fr);gap:14px}article{text-align:center;border:1px solid #7775;border-radius:18px;padding:16px}strong{display:block;min-height:28px}img{width:240px;height:240px;${appearance==='dark'?'filter:brightness(1.8)':''}}.thumb{width:64px;height:64px}</style>${cards.join('')}`);await page.locator('img').evaluateAll(es=>Promise.all(es.map(e=>e.decode())));await page.screenshot({path:`${out}/${appearance}-page-${offset/9+1}.png`,fullPage:true});}
console.log(`${files.length} corrected masters: SVG contract, normalized padding, detail/64px light/dark captures`);
}finally{await browser.close();}
