import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import { createReturningUserFixture } from '../src/demoFixture.js';

const browser = await chromium.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true }); const context = await browser.newContext({ viewport: { width: 360, height: 780 } });
const fixture = createReturningUserFixture(4); fixture.profile.rirEnabled = true; const historicalDay = fixture.program.days[0].weekday;
await context.addInitScript(state => localStorage.setItem('lift-v2-state', JSON.stringify(state)), fixture); const page = await context.newPage(); const errors = [];
await page.route('**/api/ai/status', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ available: false, provider: null }) }));
page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' });
for (const width of [360, 375, 390, 430, 500]) { await page.setViewportSize({ width, height: width === 360 ? 780 : 844 }); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `no horizontal overflow at ${width}px`); const nav = await page.locator('.bottom-nav').boundingBox(); assert.ok(nav.y + nav.height <= (width === 360 ? 781 : 845)); }
assert.equal(await page.locator('.week-strip [aria-current="date"]').count(), 1, 'calendar identifies the real current date'); assert.equal((await page.locator('.week-strip [aria-current="date"]').getAttribute('class')).includes('selected-day'), true, 'fresh app open selects today');
await page.locator('.week-strip .workout-planned:not(.selected-day)').first().click(); assert.equal(await page.locator('.week-strip .selected-day i').getAttribute('class'), 'workout-dot', 'a selected but unfinished workout remains planned, not completed'); assert.equal(await page.locator('.week-strip .selected-day i').evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(246, 245, 242)', 'selected planned workout uses the high-contrast neutral marker, not completed green'); await page.locator('.week-strip [aria-current="date"]').click();
await page.getByRole('button', { name: 'Previous week' }).click(); await page.getByRole('button', { name: new RegExp(`^${historicalDay} `) }).click(); assert.equal(await page.locator('.week-strip .selected-day i').getAttribute('class'), 'completed-dot', 'a logged historical workout receives the completed marker'); assert.equal(await page.locator('.week-strip .selected-day i').evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(127, 208, 170)', 'a selected completed workout uses a green dot'); assert.equal(await page.getByRole('button', { name: 'WORKOUT COMPLETE · VIEW HISTORY' }).count(), 1, 'previous week exposes the workout logged on that date'); assert.equal(await page.getByText('LOGGED EXERCISES', { exact: true }).count(), 1, 'historical week shows logged exercises'); assert.equal(await page.getByRole('button', { name: 'Next week' }).isEnabled(), true, 'calendar can navigate back toward the current week'); await page.getByRole('button', { name: 'Next week' }).click(); await page.locator('.week-strip .workout-planned').first().click();
await page.getByRole('button', { name: 'START WORKOUT' }).click(); const heading = page.locator('.exercise-heading h1'); await heading.evaluate(node => { node.textContent = 'Single-Arm Incline Cable Lateral Raise With Extended Name'; }); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'long exercise name does not overflow');
const firstRir = page.getByRole('combobox', { name: 'RIR for set 1' }); await firstRir.selectOption('1'); assert.equal(await firstRir.inputValue(), '1', 'RIR selection remains editable'); const rirBox = await firstRir.boundingBox(); const firstRowBox = await page.locator('.set-row').first().boundingBox(); assert.ok(rirBox.y >= firstRowBox.y && rirBox.y + rirBox.height <= firstRowBox.y + firstRowBox.height + 1, 'RIR control stays inside the compact set row'); assert.ok(firstRowBox.height <= 62, 'RIR does not create a second set row');
const weight = page.getByRole('spinbutton', { name: /Weight in kg for set 1/ }); assert.notEqual(await weight.inputValue(), '', 'a returning user receives the actual previous working load'); assert.equal(await page.getByRole('button', { name: /Increase Weight in kg for set 1/ }).isDisabled(), false, 'known working loads can use configured increments'); const before = Number(await weight.inputValue()); for (let i = 0; i < 5; i++) await page.getByRole('button', { name: /Increase Weight in kg for set 1/ }).click(); assert.ok(Number(await weight.inputValue()) > before, 'rapid increments persist after a starting load is entered');
await page.getByRole('button', { name: 'Complete set 1' }).click(); await page.getByRole('button', { name: 'Reopen set 1' }).click(); const sets = await page.locator('.set-row').count(); await page.getByRole('button', { name: '+ ADD SET' }).click(); assert.equal(await page.locator('.set-row').count(), sets + 1); const removeExtra = page.getByRole('button', { name: /^Remove extra set / }); assert.equal(await removeExtra.count(), 1, 'manually added set exposes removal'); await removeExtra.click(); assert.equal(await page.locator('.set-row').count(), sets, 'removing an added set restores the prescribed count'); assert.equal(await page.getByRole('button', { name: /^Remove extra set / }).count(), 0, 'prescribed sets cannot be removed'); assert.deepEqual(errors, []); await browser.close(); console.log('Edge QA passed: historical week navigation, responsive widths, long names, numeric controls, set correction, and reversible add-set behavior.');
