import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
import { createReturningUserFixture } from '../src/demoFixture.js';
import { exerciseCatalog } from '../src/domain.js';

const browser = await chromium.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true }); const context = await browser.newContext({ viewport: { width: 360, height: 780 } });
const fixture = createReturningUserFixture(4); fixture.profile.rirEnabled = true; for (const day of fixture.program.days) day.exercises.sort((left, right) => Number(Boolean(exerciseCatalog[right.exerciseId]?.artId)) - Number(Boolean(exerciseCatalog[left.exerciseId]?.artId))); const historicalDay = fixture.program.days[0].weekday;
await context.addInitScript(state => localStorage.setItem('lift-v2-state', JSON.stringify(state)), fixture); const page = await context.newPage(); const errors = [];
await page.route('**/api/ai/status', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ available: false, provider: null }) }));
page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); }); await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' });
for (const width of [360, 375, 390, 430, 500]) { await page.setViewportSize({ width, height: width === 360 ? 780 : 844 }); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `no horizontal overflow at ${width}px`); const nav = await page.locator('.bottom-nav').boundingBox(); assert.ok(nav.y + nav.height <= (width === 360 ? 781 : 845)); }
assert.equal(await page.locator('.week-strip [aria-current="date"]').count(), 1, 'calendar identifies the real current date'); assert.equal((await page.locator('.week-strip [aria-current="date"]').getAttribute('class')).includes('selected-day'), true, 'fresh app open selects today');
await page.locator('.week-strip .workout-planned:not(.selected-day)').first().click(); assert.equal(await page.locator('.week-strip .selected-day i').getAttribute('class'), 'workout-dot', 'a selected but unfinished workout remains planned, not completed'); await page.locator('.week-strip [aria-current="date"]').click();
await page.getByRole('button', { name: 'Previous week' }).click(); await page.getByRole('button', { name: new RegExp(`^${historicalDay} `) }).click(); assert.equal(await page.locator('.week-strip .selected-day i').getAttribute('class'), 'completed-dot', 'a logged historical workout receives the completed marker'); assert.equal(await page.getByRole('button', { name: 'WORKOUT COMPLETE · VIEW HISTORY' }).count(), 1, 'previous week exposes the workout logged on that date'); assert.equal(await page.getByText('LOGGED EXERCISES', { exact: true }).count(), 1, 'historical week shows logged exercises'); assert.equal(await page.getByRole('button', { name: 'Next week' }).isEnabled(), true, 'calendar can navigate back toward the current week'); await page.getByRole('button', { name: 'Next week' }).click(); await page.locator('.week-strip .workout-planned').first().click();
const todayOverviewRows = page.locator('.exercise-preview .exercise-list-row'); assert.equal(await todayOverviewRows.locator('img').count(), 0, 'Today overview rows are text-first even when artwork exists'); assert.equal(await todayOverviewRows.locator('.exercise-thumbnail-slot').count(), 0, 'Today reserves no thumbnail column'); const todayOverviewRow = todayOverviewRows.first();
await page.setViewportSize({ width: 390, height: 844 }); const shortMainBox = await todayOverviewRow.locator('.exercise-row-main').boundingBox(); const shortTargetBox = await todayOverviewRow.locator('.navigation-row-end').boundingBox(); assert.ok(shortMainBox.x + shortMainBox.width <= shortTargetBox.x + 1, 'a short exercise title and prescription stay on one line without overlap');
const todayTitle = todayOverviewRow.locator('strong'); const todayTarget = todayOverviewRow.locator('.navigation-row-end > span').first(); const originalTodayTitle = await todayTitle.textContent(); const originalTodayTarget = await todayTarget.textContent(); await todayTitle.evaluate(node => { node.textContent = 'Pull-ups'; }); await todayTarget.evaluate(node => { node.textContent = '3 × 6–10 · 1 RIR'; }); const pullUpMainBox = await todayOverviewRow.locator('.exercise-row-main').boundingBox(); const pullUpTargetBox = await todayOverviewRow.locator('.navigation-row-end').boundingBox(); assert.ok(Math.abs(pullUpMainBox.y + pullUpMainBox.height / 2 - (pullUpTargetBox.y + pullUpTargetBox.height / 2)) <= 1, 'Pull-ups and its longer prescription stay vertically aligned at 390px'); await todayTitle.evaluate(node => { node.textContent = 'Single-Arm Incline Cable Lateral Raise With Extended Range of Motion'; }); await page.setViewportSize({ width: 320, height: 780 }); const longTodayTitleBox = await todayTitle.boundingBox(); const narrowTodayTargetBox = await todayOverviewRow.locator('.navigation-row-end').boundingBox(); assert.ok(narrowTodayTargetBox.y >= longTodayTitleBox.y + longTodayTitleBox.height, 'a narrow Today row moves the prescription below a long exercise title'); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'long Today exercise names do not create horizontal overflow at 320px'); await todayTitle.evaluate((node, value) => { node.textContent = value; }, originalTodayTitle); await todayTarget.evaluate((node, value) => { node.textContent = value; }, originalTodayTarget); await page.setViewportSize({ width: 360, height: 780 });
await page.getByRole('button', { name: 'START WORKOUT' }).click();
const heading = page.locator('.exercise-heading h1');
const exerciseTitle = await heading.textContent();
const escapedTitle = exerciseTitle.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const artButton = page.getByRole('button', { name: new RegExp(`^View ${escapedTitle} illustration$`) });
assert.equal(await artButton.count(), 1, 'illustrated active exercise exposes one accessible detail action');
const [artBox, titleBox, replaceBox] = await Promise.all([
  artButton.boundingBox(),
  heading.boundingBox(),
  page.getByRole('button', { name: 'Replace', exact: true }).boundingBox(),
]);
assert.ok(artBox.x + artBox.width <= titleBox.x, 'illustration stays to the left of exercise information');
assert.ok(titleBox.x + titleBox.width <= replaceBox.x || titleBox.y >= replaceBox.y + replaceBox.height, 'exercise information stays clear of Replace');
await artButton.click();
assert.equal(await page.locator('.exercise-visual-viewer').count(), 1, 'tapping the illustration opens the exercise visual viewer');
await page.getByRole('button', { name: 'Close visual viewer', exact: true }).click();
await heading.evaluate(node => { node.textContent = 'Single-Arm Incline Cable Lateral Raise With Extended Name'; });
await page.setViewportSize({ width: 320, height: 780 });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'long active exercise name does not overflow at 320px');
const longTitleBox = await heading.boundingBox();
const narrowReplaceBox = await page.getByRole('button', { name: 'Replace', exact: true }).boundingBox();
assert.ok(longTitleBox.x + longTitleBox.width <= narrowReplaceBox.x || longTitleBox.y >= narrowReplaceBox.y + narrowReplaceBox.height, 'long exercise title never overlaps Replace at 320px');
await page.setViewportSize({ width: 360, height: 780 });
const firstRir = page.getByRole('combobox', { name: 'RIR for set 1' }); await firstRir.selectOption('1'); assert.equal(await firstRir.inputValue(), '1', 'RIR selection remains editable'); const rirBox = await firstRir.boundingBox(); const firstRowBox = await page.locator('.set-row').first().boundingBox(); assert.ok(rirBox.y >= firstRowBox.y && rirBox.y + rirBox.height <= firstRowBox.y + firstRowBox.height + 1, 'RIR control stays inside the compact set row'); assert.ok(firstRowBox.height <= 62, 'RIR does not create a second set row');
const weight = page.getByRole('spinbutton', { name: /Weight in kg for set 1/ }); assert.notEqual(await weight.inputValue(), '', 'a returning user receives the actual previous working load'); assert.equal(await page.getByRole('button', { name: /Increase Weight in kg for set 1/ }).isDisabled(), false, 'known working loads can use configured increments'); const before = Number(await weight.inputValue()); for (let i = 0; i < 5; i++) await page.getByRole('button', { name: /Increase Weight in kg for set 1/ }).click(); assert.ok(Number(await weight.inputValue()) > before, 'rapid increments persist after a starting load is entered');
await page.getByRole('button', { name: 'Complete set 1' }).click(); await page.getByRole('button', { name: 'Reopen set 1' }).click(); const sets = await page.locator('.set-row').count(); await page.getByRole('button', { name: '+ ADD SET' }).click(); await page.waitForFunction(expected => document.querySelectorAll('.set-row').length === expected, sets + 1); const removeExtra = page.getByRole('button', { name: /^Remove extra set / }); assert.equal(await removeExtra.count(), 1, 'manually added set exposes removal'); await removeExtra.click(); await page.waitForFunction(expected => document.querySelectorAll('.set-row').length === expected, sets); assert.equal(await page.getByRole('button', { name: /^Remove extra set / }).count(), 0, 'prescribed sets cannot be removed'); assert.deepEqual(errors, []); await browser.close(); console.log('Edge QA passed: historical week navigation, responsive widths, long names, numeric controls, set correction, and reversible add-set behavior.');
