import React,{StrictMode} from 'react';
import {createRoot} from 'react-dom/client';
import App from '/src/App.jsx';
import {createReturningUserFixture} from '/src/demoFixture.js';
import {startWorkout,saveState,loadState} from '/src/domain.js';
import {startFreestyleWorkout,addFreestyleExercise} from '/src/freestyleWorkout.js';
import {bindNavigationFocus} from '/src/navigationFocus.js';
import {observeVisibleViewport} from '/src/sheetVisibleViewport.js';
import '/src/styles.css';import '/src/overrides.css';import '/src/overlay.css';import '/src/calendar.css';import '/src/workout-controls.css';import '/src/onboarding-controls.css';import '/src/import-plan.css';import '/src/coach.css';import '/src/landing.css';import '/src/theme.css';import '/src/navigationFocus.css';import '/src/activeLoggerTouch.css';
import {createCustomExercise} from '/src/customExercises.js';
if(!import.meta.env.DEV||location.origin!=='http://127.0.0.1:4198')throw Error('Isolated review only');
const storage=window.localStorage,prefix='rook-exercise-preview:',params=new URLSearchParams(location.search);let writes=0,failWrites=false,revision=0,reduced=false;
Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>storage.getItem(prefix+k),setItem:(k,v)=>{if(failWrites)throw Error('Review storage failure');writes++;storage.setItem(prefix+k,v);},removeItem:k=>storage.removeItem(prefix+k),get length(){return Object.keys(storage).filter(k=>k.startsWith(prefix)).length;},key:i=>Object.keys(storage).filter(k=>k.startsWith(prefix))[i]?.slice(prefix.length)}});
const matchMedia=window.matchMedia.bind(window);window.matchMedia=query=>query.includes('prefers-reduced-motion')?{matches:reduced,addEventListener(){},removeEventListener(){}}:matchMedia(query);
const qa=document.createElement('details');qa.id='preview-qa';qa.innerHTML='<summary>Preview QA</summary><label>Fixture<select id="fixture"><option>Leg Press current</option><option>Empty</option><option>Queued</option><option>Current</option><option>Duplicates</option></select></label><label>Theme<select id="theme"><option>premium-dark</option><option>premium-light</option><option>dark</option><option>light</option></select></label><button id="reset">Reset fixture</button><button id="measure">Measure</button><button id="failure">Toggle save failure</button><button id="reduced">Toggle reduced motion</button><button id="broken">Break hero image</button><button id="scroll">Scroll result list</button><pre id="proof"></pre>';
const css=document.createElement('style');css.textContent='#preview-qa{position:fixed;right:0;top:0;z-index:9999;width:135px;font:10px system-ui;background:#eee;color:#111}#preview-qa label,#preview-qa button{display:block;width:100%;min-height:28px}#preview-qa select{max-width:135px}#proof{white-space:pre-wrap;max-height:100px;overflow:auto}html[data-preview-reduced] .queue-preview-added>span{animation:none}';document.head.append(css);document.body.append(qa);
const el=id=>qa.querySelector('#'+id),root=createRoot(document.getElementById('root')),releaseFocus=bindNavigationFocus(),releaseViewport=observeVisibleViewport();
function seed(){let state=startFreestyleWorkout(createReturningUserFixture(0));Object.assign(state.profile,{showExerciseImages:true,restTimerEnabled:true,appearancePreference:'dark',stylePreference:'premium',themePreference:'premium'});
 const fixture=el('fixture').value;
 if(fixture!=='Empty')state=addFreestyleExercise(state,fixture==='Current'?'hack-squat':'leg-press');
 if(['Queued','Duplicates'].includes(fixture))state=addFreestyleExercise(state,'hack-squat');
 if(fixture==='Duplicates')state=addFreestyleExercise(state,'hack-squat',{allowDuplicate:true});
 createCustomExercise(state,{id:'custom-preview',name:'Owner exceptionally long exercise name for controlled unilateral strength and endurance',equipment:['machines'],tracking:'weighted'});
 state.activeWorkout.startedAt-=120000;
 if(state.activeWorkout.exercises[0])Object.assign(state.activeWorkout.exercises[0].sets[0],{weight:52.5,reps:10,rir:2,touched:true,completed:false});
 state.activeWorkout.rest={endsAt:Date.now()+90000,seconds:90};failWrites=false;saveState(state);
}
const mount=()=>root.render(<StrictMode key={++revision}><App/></StrictMode>);
if(!params.has('resume'))seed();mount();
const theme=()=>{const value=el('theme').value;Object.assign(document.documentElement.dataset,{theme:value.startsWith('premium')?'premium':value,style:value.startsWith('premium')?'premium':'standard',appearance:value.endsWith('dark')?'dark':'light',premiumScheme:value.endsWith('dark')?'dark':'light'});};el('theme').onchange=theme;
const motionSamples=[];
const probe=event=>{const b=event.target.closest('button');if(!b?.matches('.queue-search-body,.detail-header-back,.queue-preview-actions .button'))return;const sheet=document.querySelector('.freestyle-queue-picker'),input=sheet?.querySelector('input'),top=sheet?.getBoundingClientRect().top,start=performance.now();requestAnimationFrame(()=>motionSamples.push({action:b.textContent,firstFrameMs:performance.now()-start,sameSheet:sheet===document.querySelector('.freestyle-queue-picker'),sameInput:input===sheet?.querySelector('input'),topBefore:top,topAfter:sheet?.getBoundingClientRect().top,animations:document.getAnimations().filter(a=>a.effect?.target?.matches('.queue-exercise-preview,.queue-preview-paint,.exercise-panel,.queue-preview-added>span')).map(a=>({target:a.effect.target.className,duration:a.effect.getTiming().duration,frames:a.effect.getKeyframes().map(f=>({opacity:f.opacity,transform:f.transform}))}))}));};document.addEventListener('click',probe,true);
const out=v=>el('proof').textContent=JSON.stringify(v),box=node=>{if(!node)return null;const r=node.getBoundingClientRect(),s=getComputedStyle(node);return {x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,right:r.right,paddingBottom:s.paddingBottom,background:s.backgroundColor,color:s.color,scrollHeight:node.scrollHeight,clientHeight:node.clientHeight,scrollTop:node.scrollTop};};
el('measure').onclick=()=>{const state=loadState(),sheet=document.querySelector('.freestyle-queue-picker');out({width:innerWidth,height:innerHeight,theme:el('theme').value,reduced,writes,failWrites,motionSamples,sheet:box(sheet),header:box(sheet?.querySelector('.detail-header')),hero:box(sheet?.querySelector('.queue-preview-hero')),preview:box(sheet?.querySelector('.queue-exercise-preview')),footer:box(sheet?.querySelector('.sheet-action-footer')),buttons:[...sheet?.querySelectorAll('.sheet-action-footer button')||[]].map(b=>({text:b.textContent,disabled:b.disabled,...box(b)})),layers:document.querySelectorAll('.modal-layer').length,overflow:document.documentElement.scrollWidth>innerWidth,session:state.activeWorkout});qa.open=false;};
el('reset').onclick=()=>{qa.open=false;root.render(null);seed();mount();};
el('failure').onclick=()=>{failWrites=!failWrites;out({failWrites});qa.open=false;};
el('reduced').onclick=()=>{reduced=!reduced;document.documentElement.toggleAttribute('data-preview-reduced',reduced);out({reduced});qa.open=false;};
el('broken').onclick=()=>{document.querySelector('.queue-preview-hero img')?.dispatchEvent(new Event('error'));qa.open=false;};
el('scroll').onclick=()=>{const list=document.querySelector('.exercise-search-body [data-exercise-search-scroll]');if(list)list.scrollTop=184;qa.open=false;};
if(import.meta.hot)import.meta.hot.dispose(()=>{root.unmount();releaseFocus();releaseViewport();qa.remove();css.remove();document.removeEventListener('click',probe,true);window.matchMedia=matchMedia;Object.defineProperty(window,'localStorage',{configurable:true,value:storage});});
