import { openAdjustWeek } from './qa-current-navigation.mjs';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright-core';
import { blankState, buildProgram, isoDay, weekday, WEEKDAYS, currentWeekSchedule } from '../src/domain.js';
import { addCalendarDays } from '../src/flexibleWeek.js';
const out = new URL('../artifacts/flexible-week/', import.meta.url); await mkdir(out, { recursive: true });
const browser = await chromium.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true });
for (const width of [320,390,430]) for (const appearance of ['light','dark']) for (const style of ['standard','premium']) {
  const state = blankState(), today = isoDay(), day = weekday();
  Object.assign(state.profile, { goal: 'Build muscle', experience: 'Intermediate', daysPerWeek: 3, availableDays: [day, WEEKDAYS[(WEEKDAYS.indexOf(day)+2)%7], WEEKDAYS[(WEEKDAYS.indexOf(day)+4)%7]], sessionMinutes: 60, environment: 'Commercial gym', equipment: ['full gym'], priorities: ['Balanced'], onboardingComplete: true, appearancePreference: appearance, stylePreference: style, themePreference: style === 'premium' ? 'premium' : appearance });
  state.program = buildProgram(state.profile); state.selectedDate = today; state.selectedDay = day;
  const context = await browser.newContext({ viewport: { width, height: 844 }, colorScheme: appearance, serviceWorkers: 'block' });
  await context.addInitScript(s => { if (!localStorage.getItem('lift-v2-state')) localStorage.setItem('lift-v2-state', JSON.stringify(s)); }, state);
  const page = await context.newPage(), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.route('**/api/ai/status', r => r.fulfill({ status: 200, contentType:'application/json', body:'{"available":false}' }));
  await page.goto('http://127.0.0.1:4173', { waitUntil:'networkidle' });
  const plan = await page.evaluate(() => JSON.parse(localStorage.getItem('lift-v2-state')).program);
  const shot = async name => { await page.waitForTimeout(350); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true); await page.screenshot({ path: fileURLToPath(new URL(`${width}-${style}-${appearance}-${name}.png`,out)) }); };
  await shot('01-today');
  await openAdjustWeek(page);
  await shot('02-menu');
  await page.getByRole('button',{name:/Move a workout Choose/}).click();
  await shot('03-picker');
  const name = currentWeekSchedule(state).find(s => s.scheduledDate === today).workout.name;
  await page.locator('.flexible-week-sheet .choice-row').filter({hasText:name}).first().click();
  await shot('04-dates');
  const tomorrow = addCalendarDays(today,1);
  const date = new Intl.DateTimeFormat('en',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${tomorrow}T12:00:00`));
  await page.locator('.flexible-week-dates').getByRole('button',{name:date,exact:true}).click();
  await shot('05-review');
  await page.getByRole('button',{name:'USE THIS SCHEDULE',exact:true}).click();
  await shot('06-source');
  assert.equal(await page.getByRole('button',{name:'START WORKOUT',exact:true}).count(),0);
  await page.getByRole('button',{name:'VIEW DESTINATION',exact:true}).click();
  await shot('07-destination');
  assert.equal(await page.getByRole('button',{name:'START WORKOUT',exact:true}).count(),1);
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('lift-v2-state')));
  assert.deepEqual(saved.program, plan, 'plan unchanged');
  assert.equal(Object.keys(saved.flexibleWeek.sessions).length,1);
  await context.setOffline(true);
  await openAdjustWeek(page);
  await page.getByRole('button', { name: 'Close Adjust week', exact: true }).click();
  await context.setOffline(false);
  await page.reload({waitUntil:'networkidle'});
  assert.deepEqual((await page.evaluate(() => JSON.parse(localStorage.getItem('lift-v2-state')))).flexibleWeek, saved.flexibleWeek);
  await openAdjustWeek(page);
  await page.getByRole('button',{name:'Restore original schedule',exact:true}).click();
  await shot('08-restore');
  await page.getByRole('button',{name:'USE THIS SCHEDULE',exact:true}).click();
  assert.deepEqual(errors,[]); await context.close();
}
await browser.close(); console.log('Flexible Week runtime: 12 width/theme flows passed.');
