import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';

const browser = await chromium.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: 'block' }); const page = await context.newPage(); const errors = []; let planRequests = 0;
await page.route('**/api/ai/status', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ available: false, provider: null }) }));
await page.route('**/api/ai', route => { const operation = route.request().postDataJSON()?.operation; if (operation === 'plan') planRequests += 1; return ['plan', 'coach'].includes(operation) ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'AI disabled for deterministic local-fallback QA.' }) }) : route.continue(); });
page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'BUILD MY PLAN' }).click();
assert.equal(await page.getByRole('combobox', { name: 'Sex' }).count(), 0, 'onboarding does not require a demographic that does not change the plan');
await page.getByRole('combobox', { name: 'Age range' }).click(); await page.getByRole('option', { name: '30–39' }).click(); await page.getByRole('button', { name: 'CONTINUE' }).click();
await page.getByRole('button', { name: 'Lose fat' }).click(); await page.getByRole('button', { name: 'CONTINUE' }).click();
await page.getByRole('button', { name: 'Beginner' }).click(); await page.getByRole('button', { name: 'CONTINUE' }).click();
await page.getByRole('button', { name: '3 days' }).click();
await page.getByRole('checkbox', { name: 'Make any day available' }).check(); assert.equal(await page.getByRole('checkbox', { name: 'Make any day available' }).isChecked(), true, 'Any day is a checkbox rather than a day card');
await page.getByRole('button', { name: '60 min' }).click(); await page.getByRole('button', { name: 'CONTINUE' }).click();
await page.getByRole('button', { name: 'Commercial gym' }).click(); await page.getByRole('button', { name: 'CONTINUE' }).click();
await page.getByRole('button', { name: 'Balanced' }).click(); await page.getByRole('button', { name: 'CONTINUE' }).click(); assert.equal(await page.getByRole('button', { name: /Balanced starting point/ }).getAttribute('aria-pressed'), 'true', 'balanced effort is selected by default'); await page.getByRole('button', { name: 'CONTINUE' }).click();
await page.emulateMedia({ reducedMotion: 'reduce' }); await page.getByRole('button', { name: 'BUILD MY PLAN' }).click();
await page.getByRole('heading', { name: 'Building your training week…' }).waitFor();
assert.equal(await page.locator('.building-spinner').evaluate(element => getComputedStyle(element).animationName), 'none', 'reduced-motion removes the spinner animation');
assert.equal(await page.getByText(/Step \d of 4/).count(), 0, 'fast generation does not show theatrical step counters');
assert.equal(await page.getByRole('button', { name: 'CANCEL' }).count(), 0, 'cancel does not flash during a brief local operation');
const buildStarted = Date.now() - 300;
await page.getByRole('heading', { name: 'Your week is ready.' }).waitFor({ timeout: 90000 }).catch(async error => { console.error(await page.locator('body').innerText()); throw error; });
const buildElapsedMs = Date.now() - buildStarted; assert.ok(buildElapsedMs >= 1400 && buildElapsedMs < 3000, `local personalized plan uses a brief, bounded transition (${buildElapsedMs}ms)`);
assert.equal(planRequests, 0, 'standard questionnaire plan generation does not wait for a network AI request');
assert.equal(await page.getByText('Full Body A / B / C', { exact: true }).count(), 1, 'three days selects the fixed full-body structure');
assert.equal(await page.getByRole('region', { name: 'How your answers shaped this plan' }).count(), 1, 'the first plan view visibly reflects onboarding constraints');
for (const value of ['Lose fat · Beginner', '3 sessions · Mon, Wed, Fri', 'Up to 60 min', 'Full gym']) assert.equal(await page.getByText(value, { exact: true }).count(), 1, `personalization summary shows ${value}`);
assert.equal(await page.getByText('WEEKLY CONDITIONING', { exact: true }).count(), 1, 'fat-loss preview explains the separate conditioning prescription');
assert.equal(await page.getByText('2 × 30 min', { exact: true }).count(), 1, 'conditioning scales to the selected strength frequency and session duration');
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'goal and plan UI do not overflow the phone viewport');
const previewFunnel = await page.evaluate(() => JSON.parse(localStorage.getItem('lift-funnel-events-v1')).map(event => event.name)); for (const event of ['app_open', 'onboarding_started', 'onboarding_step_viewed', 'onboarding_step_completed', 'plan_generation_started', 'plan_generation_completed', 'first_plan_viewed']) assert.equal(previewFunnel.includes(event), true, `${event} is measurable`);
await page.getByRole('button', { name: 'USE THIS PLAN' }).click();
await page.waitForFunction(() => Boolean(JSON.parse(localStorage.getItem('lift-v2-state'))?.profile?.onboardingComplete), null, { timeout: 90000 });
const selectFirstPlannedDay = async () => { if (await page.getByRole('button', { name: 'START WORKOUT' }).isVisible()) return; const day = await page.evaluate(() => JSON.parse(localStorage.getItem('lift-v2-state')).program.days[0].weekday); await page.getByRole('button', { name: new RegExp(`^${day} `) }).click(); };
await selectFirstPlannedDay();
await page.getByRole('button', { name: 'START WORKOUT' }).waitFor({ timeout: 90000 });
const persistedBeforeReload = await page.evaluate(() => { const state = JSON.parse(localStorage.getItem('lift-v2-state')); return { programId: state.program.id, programSource: state.program.source, profile: state.profile, programName: state.program.name }; });
await page.reload({ waitUntil: 'networkidle' }); await selectFirstPlannedDay(); const persistedAfterReload = await page.evaluate(() => { const state = JSON.parse(localStorage.getItem('lift-v2-state')); return { programId: state.program.id, programSource: state.program.source, profile: state.profile, programName: state.program.name }; });
assert.equal(persistedAfterReload.programId, persistedBeforeReload.programId, 'reload uses the same persisted program'); assert.equal(persistedAfterReload.profile.goal, 'Lose fat'); assert.match(persistedAfterReload.profile.effortStyle, /^Balanced workload/, 'balanced effort persists as the default'); assert.deepEqual(persistedAfterReload.profile.availableDays, ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']); const authoredDays = await page.evaluate(() => JSON.parse(localStorage.getItem('lift-v2-state')).program.days.map(day => day.weekday)); assert.equal(authoredDays.length, 3, 'Rook schedules exactly the requested number of days'); assert.equal(new Set(authoredDays).size, 3, 'scheduled weekdays are distinct'); assert.equal(authoredDays.every(day => persistedAfterReload.profile.availableDays.includes(day)), true, 'Rook chooses only from user availability');
assert.equal(persistedAfterReload.programSource, 'fixed-template', 'the evidence-informed local template is persisted');
assert.equal(await page.getByText(/first session/i).count() > 0, true, 'fresh plan exposes first-session states');
assert.equal(await page.getByText(/^Last /).count(), 0, 'fresh user has no previous-session claims');
const firstExerciseName = await page.locator('.exercise-preview strong').first().textContent(); await page.getByRole('button', { name: 'PROFILE' }).click(); assert.equal(await page.getByRole('heading', { name: new RegExp(persistedBeforeReload.programName) }).count(), 1, 'Profile reflects the persisted program'); assert.equal(await page.getByText('Mon–Sun', { exact: true }).count(), 1, 'Profile reflects all available onboarding weekdays in compact form');
assert.equal(await page.getByRole('button', { name: 'Log out' }).count(), 1, 'Profile exposes a local logout/reset action');
assert.equal(await page.getByRole('button', { name: 'Replace plan' }).count(), 1, 'Profile exposes plan replacement'); await page.getByRole('button', { name: 'Replace plan' }).click(); await page.getByRole('button', { name: 'Import from Notes' }).click(); assert.equal(await page.getByRole('heading', { name: 'Bring your existing workout into Rook.' }).count(), 1, 'Notes import opens a paste-and-preview flow'); await page.getByRole('button', { name: 'Close', exact: true }).click();
await page.getByRole('button', { name: 'PROGRESS' }).click(); assert.equal(await page.getByText(/Complete your first workout/).count(), 1, 'fresh progress is empty');
await page.getByRole('button', { name: 'COACH' }).click(); await page.getByRole('textbox', { name: 'Ask Coach' }).fill(`Should I increase ${firstExerciseName}?`); await page.getByRole('button', { name: 'Send message' }).click(); await page.waitForFunction(() => JSON.parse(localStorage.getItem('lift-v2-state')).conversations.at(-1)?.reply?.source === 'deterministic');
assert.equal(await page.locator('.coach-message').count() > 0, true, 'Coach replies render in a distinct response card'); const coachInputBox = await page.locator('.coach-input').boundingBox(); const coachNavBox = await page.locator('.bottom-nav').boundingBox(); assert.ok(Math.abs(coachInputBox.y + coachInputBox.height - coachNavBox.y) < 2, `Coach input stays directly above bottom navigation (${coachInputBox.y + coachInputBox.height}/${coachNavBox.y})`);
const navBox = await page.locator('.bottom-nav').boundingBox(); assert.ok(Math.abs(navBox.y + navBox.height - 844) < 2, 'navigation is fixed to viewport bottom'); assert.equal(await page.locator('.bottom-nav button span').count(), 4, 'navigation is text-only');
await page.getByRole('button', { name: 'TODAY', exact: true }).click(); await page.getByRole('button', { name: 'START WORKOUT' }).click();
const actionFunnel = await page.evaluate(() => JSON.parse(localStorage.getItem('lift-funnel-events-v1')).map(event => event.name)); assert.equal(actionFunnel.includes('onboarding_completed'), true); assert.equal(actionFunnel.includes('first_workout_started'), true);
assert.equal(await page.getByRole('spinbutton', { name: /Weight in kg for set 1/ }).inputValue(), '', 'first weight is unset');
await page.getByRole('spinbutton', { name: /Weight in kg for set 1/ }).fill('20'); await page.getByRole('button', { name: 'Complete set 1' }).click(); await page.reload({ waitUntil: 'networkidle' });
await page.getByRole('button', { name: 'RESUME WORKOUT' }).click(); assert.equal(await page.getByRole('button', { name: 'Reopen set 1' }).count(), 1, 'active workout persists');
await page.getByRole('button', { name: 'Back to Today' }).click(); await page.getByRole('button', { name: 'COACH' }).click(); await page.getByRole('textbox', { name: 'Ask Coach' }).fill('Adapt today to 35 minutes.'); await page.getByRole('button', { name: 'Send message' }).click(); await page.getByRole('button', { name: 'APPLY TO TODAY' }).waitFor();
const before = await page.evaluate(() => JSON.parse(localStorage.getItem('lift-v2-state')).activeWorkout.exercises.length); assert.ok(before > 1); await page.getByRole('button', { name: 'APPLY TO TODAY' }).click(); const after = await page.evaluate(() => JSON.parse(localStorage.getItem('lift-v2-state')).activeWorkout.exercises.length); assert.ok(after <= before, 'Coach mutation applies only after acceptance');
assert.deepEqual(errors, [], `browser console remains clean: ${errors.join('; ')}`); await browser.close(); console.log(`Functional QA passed: local plan preview opened in ${buildElapsedMs}ms with no plan AI request; persistence and Coach mutation also passed.`);
