import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright-core';

const root = new URL('../artifacts/scratch-plan/', import.meta.url); await mkdir(root, { recursive: true });
const output = name => fileURLToPath(new URL(name, root));
const appUrl = process.env.ROOK_QA_URL || 'http://127.0.0.1:4173';
const browser = await chromium.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: 'block' });
const page = await context.newPage(); const errors = [];
page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
await page.route('**/api/ai/status', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ available: false }) }));
await page.goto(`${appUrl}/?scratch-plan-qa=1`, { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /Start from scratch/i }).click();
await page.getByRole('heading', { name: 'Create your own week.' }).waitFor();
assert.equal(await page.getByText('Choose your training days, then build each workout yourself.', { exact: true }).count(), 1);
assert.equal(await page.getByText('Choose at least one day', { exact: true }).count(), 1);
assert.equal(await page.getByRole('button', { name: 'Clear', exact: true }).count(), 0);
assert.equal(await page.getByRole('button', { name: 'CONTINUE' }).isDisabled(), true);
for (const day of ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'])
  assert.equal(await page.getByRole('button', { name: day, exact: true }).count(), 1, `${day} uses an unambiguous visible label`);
for (const width of [320, 375, 390, 430, 500]) {
  await page.setViewportSize({ width, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true, `${width}px has no horizontal overflow`);
  await page.screenshot({ path: output(`${width}-setup-empty.png`), fullPage: false });
}
await page.setViewportSize({ width: 390, height: 844 });
await page.getByLabel('Weekly plan name').fill('My Strength Week');
for (const day of ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'])
  await page.getByRole('button', { name: day, exact: true }).click();
assert.equal(await page.getByText('6 training days selected', { exact: true }).count(), 1);
assert.equal(await page.getByText('Up to 6 training days', { exact: true }).count(), 1);
assert.equal(await page.getByRole('button', { name: 'Sun', exact: true }).isDisabled(), true, 'the seventh day is unavailable at the six-day limit');
await page.screenshot({ path: output('390-six-day-limit.png'), fullPage: false });
await page.getByRole('button', { name: 'Clear', exact: true }).click();
assert.equal(await page.getByText('Choose at least one day', { exact: true }).count(), 1);
assert.equal(await page.getByRole('button', { name: 'CONTINUE' }).isDisabled(), true);
await page.getByRole('button', { name: 'Mon', exact: true }).click();
await page.getByRole('button', { name: 'Thu', exact: true }).click();
assert.equal(await page.getByText('2 training days selected', { exact: true }).count(), 1);
assert.equal(await page.getByRole('button', { name: 'Clear', exact: true }).count(), 1);
assert.equal(await page.getByRole('button', { name: 'CONTINUE' }).isEnabled(), true);
await page.screenshot({ path: output('390-setup.png'), fullPage: false });
await page.getByRole('button', { name: 'CONTINUE' }).click();
assert.equal(await page.getByRole('button', { name: 'USE THIS PLAN' }).isDisabled(), true, 'blank workouts cannot be saved');
assert.equal(await page.getByRole('switch', { name: 'Recommended warm-ups', exact: true }).count(), 1);
assert.equal(await page.getByText('Ramp-up sets are controlled separately.', { exact: true }).count(), 1);
assert.equal(await page.getByText('Add an exercise to each day to continue.', { exact: true }).count(), 1);
assert.equal(await page.locator('.scratch-workout-day.is-incomplete').count(), 2);
assert.equal(await page.getByRole('button', { name: '+ Add first exercise', exact: true }).count(), 2);
assert.equal(await page.getByText('EDITABLE', { exact: true }).count(), 0);
await page.screenshot({ path: output('390-editor-empty.png'), fullPage: false });

async function addExercise(day, query, name) {
  const daySection = page.locator('.import-day').filter({ has: page.getByLabel(`${day} workout name`) });
  await daySection.getByRole('button', { name: /\+ Add (first )?exercise/ }).click();
  const search = daySection.getByLabel(`Search exercise for ${day}`);
  assert.equal(await search.evaluate(node => document.activeElement === node), false, `${day} exercise picker does not summon the keyboard when opened`);
  await search.fill(query);
  await daySection.getByRole('option', { name, exact: true }).click();
}
await addExercise('Mon', 'Bench Press', 'Bench Press');
const monDay = page.locator('.scratch-workout-day').filter({ has: page.getByLabel('Mon workout name') });
const thuDay = page.locator('.scratch-workout-day').filter({ has: page.getByLabel('Thu workout name') });
await monDay.locator('.scratch-day-status .ready').waitFor();
assert.equal(await monDay.locator('.scratch-day-status').innerText(), '1 exercise');
assert.equal(await page.getByText('Thu still needs an exercise.', { exact: true }).count(), 1);
await page.evaluate(() => scrollTo(0, 0));
await page.screenshot({ path: output('390-editor-one-exercise.png'), fullPage: false });
await monDay.getByRole('button', { name: /Workout options/ }).click();
await page.getByRole('button', { name: 'Copy exercises to another day', exact: true }).click();
await page.getByRole('radio', { name: /Thu/ }).click();
await page.getByRole('button', { name: 'COPY', exact: true }).click();
await page.locator('.plan-workout-actions-sheet').waitFor({state:'detached'});
await thuDay.locator('.scratch-day-status .ready').waitFor();
assert.equal(await thuDay.locator('.scratch-day-status').innerText(), '1 exercise', 'copying a filled day populates an empty selected day');
assert.equal(await page.locator('.plan-editor-exercise').count(), 2);
assert.equal(await page.locator('.scratch-workout-day.is-ready').count(), 2);
assert.equal(await page.locator('.scratch-readiness').count(), 0);
await page.getByLabel('Mon workout name').fill('');
await page.getByText('Enter a name for each workout to continue.', { exact: true }).waitFor();
assert.equal(await monDay.locator('.scratch-day-status .validation-error').count(), 1);
assert.equal(await page.locator('.scratch-workout-day.is-ready').count(), 1, 'overall progress requires a valid workout name');
assert.equal(await page.getByRole('button', { name: 'USE THIS PLAN' }).isDisabled(), true);
await page.getByLabel('Mon workout name').fill('Mon Workout');
assert.equal(await page.locator('.scratch-workout-day.is-ready').count(), 2);
assert.equal(await page.locator('.scratch-readiness').count(), 0);
await monDay.getByRole('button', { name: /Workout options/ }).click();
await page.getByRole('button', { name: 'Collapse workout', exact: true }).click();
await page.locator('.plan-workout-actions-sheet').waitFor({state:'detached'});
assert.equal(await monDay.getByRole('button', { name: /Workout options/ }).count(), 1);
assert.equal(await page.locator('.plan-editor-exercise').count(), 1, 'collapsed ready day becomes summary-driven');
await page.evaluate(() => scrollTo(0, 0));
await page.screenshot({ path: output('390-editor-ready-summary.png'), fullPage: false });
await monDay.getByRole('button', { name: /Workout options/ }).click();
await page.getByRole('button', { name: 'Expand workout', exact: true }).click();
await page.locator('.plan-workout-actions-sheet').waitFor({state:'detached'});
assert.equal(await page.locator('.plan-editor-exercise').count(), 2);
assert.equal(await page.getByRole('button', { name: 'USE THIS PLAN' }).isEnabled(), true);
await page.evaluate(() => scrollTo(0, 0));
await page.screenshot({ path: output('390-editor.png'), fullPage: false });
await page.getByRole('button', { name: 'USE THIS PLAN' }).click();
await page.getByRole('button', { name: 'TODAY', exact: true }).waitFor();
let stored = await page.evaluate(() => JSON.parse(localStorage.getItem('lift-v2-state')));
assert.equal(stored.profile.onboardingComplete, true);
assert.equal(stored.program.name, 'My Strength Week');
assert.equal(stored.program.source, 'manual');
assert.deepEqual(stored.program.days.map(day => day.weekday), ['Mon', 'Thu']);
assert.deepEqual(stored.program.days.map(day => day.exercises.length), [1, 1]);
await page.screenshot({ path: output('390-today.png'), fullPage: false });
await page.reload({ waitUntil: 'networkidle' });
stored = await page.evaluate(() => JSON.parse(localStorage.getItem('lift-v2-state')));
assert.equal(stored.program?.source, 'manual', 'manual plan remains valid after refresh');
assert.equal(await page.getByRole('button', { name: 'TODAY', exact: true }).count(), 1);
assert.deepEqual(errors, []);
await context.close(); await browser.close();
console.log('Scratch plan QA passed: landing entry, day setup, empty-plan safeguards, manual exercise creation, persistence, and Today handoff are correct.');
