import React from 'react';
import {createRoot} from 'react-dom/client';
import App from '/src/App.jsx';
import {createReturningUserFixture} from '/src/demoFixture.js';
import {saveState,loadState} from '/src/domain.js';
import {startFreestyleWorkout,addFreestyleExercise} from '/src/freestyleWorkout.js';
import {templateDraft,saveWorkoutTemplate} from '/src/savedWorkouts.js';
import {bindNavigationFocus} from '/src/navigationFocus.js';
import {observeVisibleViewport} from '/src/sheetVisibleViewport.js';
import '/src/styles.css';import '/src/overrides.css';import '/src/overlay.css';import '/src/calendar.css';import '/src/workout-controls.css';import '/src/onboarding-controls.css';import '/src/import-plan.css';import '/src/coach.css';import '/src/landing.css';import '/src/theme.css';import '/src/navigationFocus.css';import '/src/activeLoggerTouch.css';
if(!import.meta.env.DEV||location.origin!=='http://127.0.0.1:4198')throw Error('Isolated development review only');
const params=new URLSearchParams(location.search),theme=params.get('theme')||'premium-dark',native=window.localStorage,prefix='rook-search-keyboard-review:';
Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>native.getItem(prefix+k),setItem:(k,v)=>native.setItem(prefix+k,v),removeItem:k=>native.removeItem(prefix+k)}});
let state=startFreestyleWorkout(createReturningUserFixture(1));
Object.assign(state.profile,{restTimerEnabled:false,appearancePreference:theme.endsWith('dark')?'dark':'light',stylePreference:theme.startsWith('premium')?'premium':'standard',themePreference:theme.startsWith('premium')?'premium':theme.endsWith('dark')?'dark':'light'});
const example=addFreestyleExercise(state,'leg-press');
for(let i=1;i<=16;i++)state=saveWorkoutTemplate(state,{...templateDraft(example.activeWorkout,example),name:`Squat routine ${i}`},{id:`search-review-${i}`});
saveState(state);
const releaseViewport=observeVisibleViewport(),releaseFocus=bindNavigationFocus(),root=createRoot(document.getElementById('root'));root.render(<App/>);
window.searchKeyboardReview={state:()=>loadState()};
if(import.meta.hot)import.meta.hot.dispose(()=>{root.unmount();releaseViewport();releaseFocus();Object.defineProperty(window,'localStorage',{configurable:true,value:native});delete window.searchKeyboardReview;});
