import React,{StrictMode} from 'react';
import {createRoot} from 'react-dom/client';
import App,{PlanEditor,EntryLanding} from '/src/App.jsx';
import {createReturningUserFixture} from '/src/demoFixture.js';
import {startWorkout,saveState,loadState,blankState,isoDay,weekday} from '/src/domain.js';
import {startFreestyleWorkout,addFreestyleExercise} from '/src/freestyleWorkout.js';
import {saveWorkoutTemplate,templateDraft} from '/src/savedWorkouts.js';
import {dayOverflowFixture} from '/src/dayOverflow.fixture.js';
import {todayMissedRestFixture} from '/src/todayMissedRest.fixture.js';
import {combineSources,buildCombinedProposal} from '/src/combineWorkouts.js';
import {AIService} from '/src/aiService.js';
import {StartupRecovery} from '/src/StartupBoundary.jsx';
import {bindNavigationFocus} from '/src/navigationFocus.js';
import {observeVisibleViewport} from '/src/sheetVisibleViewport.js';
import '/src/styles.css';import '/src/overrides.css';import '/src/overlay.css';import '/src/calendar.css';import '/src/workout-controls.css';import '/src/onboarding-controls.css';import '/src/import-plan.css';import '/src/coach.css';import '/src/landing.css';import '/src/theme.css';import '/src/navigationFocus.css';import '/src/activeLoggerTouch.css';
if(!import.meta.env.DEV||location.origin!=='http://127.0.0.1:4198')throw Error('Isolated review only');
AIService.coach=async()=>({text:'Synthetic local review response.'});
const vv=new EventTarget();Object.assign(vv,{height:innerHeight,width:innerWidth,offsetTop:0,scale:1});Object.defineProperty(window,'visualViewport',{configurable:true,value:vv});
let keyboardModel=false;const resizeModel=()=>{if(!keyboardModel)Object.assign(vv,{height:innerHeight,width:innerWidth,offsetTop:0});vv.dispatchEvent(new Event('resize'));};window.addEventListener('resize',resizeModel);
const storage=window.localStorage,prefix='rook-spacing:',params=new URLSearchParams(location.search);let revision=0;
Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>storage.getItem(prefix+k),setItem:(k,v)=>storage.setItem(prefix+k,v),removeItem:k=>storage.removeItem(prefix+k)}});
const qa=document.createElement('details');qa.id='spacing-qa';qa.innerHTML='<summary>Spacing QA</summary><label>Scenario<select id="scenario"><option>Repeated workout</option><option>Planned workout</option><option>Imported note</option><option>Freestyle workout</option><option>Freestyle with template</option><option>Empty freestyle</option><option>Today workout</option><option>Rest day</option><option>Missed workouts</option><option>Completed workouts</option><option>Coach populated</option><option>Coach combine</option><option>Plan editor</option><option>Landing</option><option>Recovery</option></select></label><label>Theme<select id="theme"><option>premium-dark</option><option>premium-light</option><option>dark</option><option>light</option></select></label><button id="reset">Reset scenario</button><button id="measure">Measure spacing</button><button id="bottom">Scroll bottom</button><button id="top">Scroll top</button><button id="keyboard">Toggle keyboard model</button><pre id="proof"></pre>';
const css=document.createElement('style');css.textContent='#spacing-qa{position:fixed;right:0;top:0;z-index:99999;width:116px;font:10px system-ui;background:#eee;color:#111}#spacing-qa label,#spacing-qa button{display:block;width:100%;min-height:28px}#spacing-qa select{max-width:116px}#proof{white-space:pre-wrap;max-height:80px;overflow:auto}';document.head.append(css);document.body.append(qa);
const el=id=>qa.querySelector('#'+id),root=createRoot(document.getElementById('root')),releaseFocus=bindNavigationFocus(),releaseViewport=observeVisibleViewport();
const names=['Straight Bar Cable Pushdown','Single-Leg Leg Extension','Step-down','Single-Leg Hamstring Curl','Calf Raises na Leg Press mašini'];
function seed(){const scenario=el('scenario').value;if(scenario==='Landing')return blankState();let state=['Rest day','Missed workouts'].includes(scenario)?todayMissedRestFixture({count:scenario==='Rest day'?0:3}):scenario==='Completed workouts'?dayOverflowFixture({count:2}):createReturningUserFixture(0);
 Object.assign(state.profile,{showExerciseImages:true,restTimerEnabled:true,rirEnabled:true,appearancePreference:'dark',stylePreference:'premium',themePreference:'premium'});
 if(!['Rest day','Missed workouts','Completed workouts'].includes(scenario)){state.program.name='Upper Strength and Hypertrophy A';state.program.days[0].name='Upper Strength and Hypertrophy A';state.program.days[0].exercises.forEach((e,i)=>{e.importedName=names[i%names.length];e.notes=i===1?'Keep a controlled tempo.\nStop before discomfort.':'';});}
 if(scenario==='Imported note'){const source='3x8 or 3x12 — controlled tempo.';state.program.importMetadata={sourceNotes:[{text:source}]};state.program.days[0].exercises[0].notes=source;}
 if(scenario==='Today workout'){state.program.days[0].weekday=weekday();state.selectedDate=isoDay();state.selectedDay=weekday();}
 if(['Repeated workout','Planned workout','Imported note'].includes(scenario)){state.activeWorkout=startWorkout(state,{...state.program.days[0],exercises:state.program.days[0].exercises.slice(0,5)});if(scenario==='Repeated workout')state.activeWorkout.source='repeat';}
 if(['Freestyle workout','Freestyle with template','Empty freestyle'].includes(scenario)){state=startFreestyleWorkout(state);if(scenario!=='Empty freestyle')for(const id of ['hack-squat','leg-press','split-squat','plank'])state=addFreestyleExercise(state,id);}
 if(state.activeWorkout){const active=state.activeWorkout;active.startedAt-=120000;active.rest={endsAt:Date.now()+1200000,seconds:1200};if(active.exercises.length){active.exercises[0].sets.forEach((s,i)=>Object.assign(s,{weight:52.5,reps:10,rir:2,added:i===1}));if(active.exercises[1])active.exercises[1].startedAt=Date.now()-60000;}
  if(scenario==='Freestyle workout')state.workouts=[{id:'previous',name:'Earlier freestyle',completedAt:new Date(Date.now()-86400000).toISOString(),exercises:[{...structuredClone(active.exercises[0]),sets:[{weight:90,reps:7,rir:2,completed:true}]}]}];
 }
 if(scenario==='Freestyle with template')state=saveWorkoutTemplate(state,templateDraft({...state.program.days[0],exercises:state.program.days[0].exercises.slice(0,3)},state),{id:'spacing-template'});
 if(scenario.startsWith('Coach')){state.activeCoachConversationId='spacing-chat';delete state.coachConversationMeta;state.conversations=Array.from({length:3},(_,i)=>({id:'spacing-message-'+i,conversationId:'spacing-chat',createdAt:Date.now(),user:'How should I approach my next training session?',reply:{text:'Use your current targets and record the work you perform. Review any proposed adjustment before applying it.'}}));state.conversations.unshift({id:'earlier-chat',conversationId:'earlier-chat',createdAt:Date.now()-86400000,user:'Earlier training question',reply:{text:'Previous advice remains available.'}});if(scenario==='Coach combine'){const sources=combineSources(state).slice(0,2),result=buildCombinedProposal(state,{sourceIds:sources.map(s=>s.logicalSessionId),minutes:60});if(result.status==='ready')state.conversations.at(-1).reply={text:'Review the combined workout before applying it.',action:{type:'combine-workouts',proposal:result.proposal}};}}
 if(scenario==='Landing')state=blankState();saveState(state);return state;
}
const theme=()=>{const value=el('theme').value;Object.assign(document.documentElement.dataset,{theme:value.startsWith('premium')?'premium':value,style:value.startsWith('premium')?'premium':'standard',appearance:value.endsWith('dark')?'dark':'light',premiumScheme:value.endsWith('dark')?'dark':'light'});};el('theme').onchange=theme;
function mount(state){const scenario=el('scenario').value;root.render(<StrictMode key={++revision}>{scenario==='Landing'?<div className="app-shell"><EntryLanding personalize={()=>{}} importPlan={()=>{}} startFromScratch={()=>{}} restoreBackup={()=>{}}/></div>:scenario==='Plan editor'?<div className="app-shell"><main className="screen detail-screen edit-plan-screen"><PlanEditor mode="edit" source={state.program} profile={state.profile} exerciseState={state} onSave={()=>{}} onCancel={()=>{}}/></main></div>:scenario==='Recovery'?<StartupRecovery startup={{code:'parse-error',recovery:{createdAt:Date.now()-3600000}}} onRetry={()=>{}} renderImport={()=>null}/>:<App/>}</StrictMode>);}
if(params.get('case'))el('scenario').value=params.get('case');mount(seed());
const box=node=>{if(!node)return null;const r=node.getBoundingClientRect(),s=getComputedStyle(node);return {x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,right:r.right,marginTop:s.marginTop,marginBottom:s.marginBottom,paddingTop:s.paddingTop,paddingBottom:s.paddingBottom};};
el('reset').onclick=()=>{qa.open=false;el('proof').textContent='';root.render(null);mount(seed());};
el('measure').onclick=()=>{qa.open=false;const cancel=[...document.querySelectorAll('#root button')].find(b=>b.textContent==='Cancel repeated workout'),queue=document.querySelector('.up-next');el('proof').textContent=JSON.stringify({width:innerWidth,height:innerHeight,theme:el('theme').value,scenario:el('scenario').value,overflow:document.documentElement.scrollWidth>innerWidth,queue:box(queue),cancel:box(cancel),gap:queue&&cancel?cancel.getBoundingClientRect().top-queue.getBoundingClientRect().bottom:null,timer:box(document.querySelector('.rest-timer')),footer:box(document.querySelector('.sheet-action-footer')),buttons:[...document.querySelectorAll('#root button')].filter(b=>b.getBoundingClientRect().height).map(b=>({text:(b.getAttribute('aria-label')||b.textContent).slice(0,100),...box(b)})),session:loadState().activeWorkout});};
el('bottom').onclick=()=>{qa.open=false;const scroller=[...document.querySelectorAll('.modal-layer [data-exercise-search-scroll],.modal-layer .sheet-scroll,.modal-layer .profile-setting-scroll,.modal-layer .detail-screen')].find(e=>e.getBoundingClientRect().height&&e.scrollHeight>e.clientHeight)||document.scrollingElement;scroller.scrollTop=scroller.scrollHeight;};
el('keyboard').onclick=()=>{keyboardModel=!keyboardModel;const field=document.querySelector('.modal-layer input,.modal-layer textarea,.coach-input textarea');if(keyboardModel)field?.focus({preventScroll:true});Object.assign(vv,{height:keyboardModel?430:innerHeight,offsetTop:keyboardModel?24:0,width:innerWidth});vv.dispatchEvent(new Event('resize'));vv.dispatchEvent(new Event('scroll'));qa.open=false;};
el('top').onclick=()=>{qa.open=false;const scroller=[...document.querySelectorAll('.modal-layer [data-exercise-search-scroll],.modal-layer .sheet-scroll,.modal-layer .profile-setting-scroll,.modal-layer .detail-screen')].find(e=>e.getBoundingClientRect().height&&e.scrollHeight>e.clientHeight)||document.scrollingElement;scroller.scrollTop=0;};
if(import.meta.hot)import.meta.hot.dispose(()=>{root.unmount();releaseFocus();releaseViewport();window.removeEventListener('resize',resizeModel);qa.remove();css.remove();Object.defineProperty(window,'localStorage',{configurable:true,value:storage});});
