import React,{StrictMode} from 'react';
import {createRoot} from 'react-dom/client';
import App from '/src/App.jsx';
import {createReturningUserFixture} from '/src/demoFixture.js';
import {saveState,loadState} from '/src/domain.js';
import {startFreestyleWorkout,addFreestyleExercise} from '/src/freestyleWorkout.js';
import {bindNavigationFocus} from '/src/navigationFocus.js';
import {observeVisibleViewport} from '/src/sheetVisibleViewport.js';
import '/src/styles.css';import '/src/overrides.css';import '/src/overlay.css';import '/src/calendar.css';import '/src/workout-controls.css';import '/src/onboarding-controls.css';import '/src/import-plan.css';import '/src/coach.css';import '/src/landing.css';import '/src/theme.css';import '/src/navigationFocus.css';import '/src/activeLoggerTouch.css';
if(!import.meta.env.DEV||location.origin!=='http://127.0.0.1:4198')throw Error('Isolated review only');
const storage=window.localStorage,prefix='rook-use-values:',params=new URLSearchParams(location.search);let writes=0,failWrites=false,revision=0,reduced=false;
Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>storage.getItem(prefix+k),setItem:(k,v)=>{if(failWrites)throw Error('Review storage failure');writes++;storage.setItem(prefix+k,v);},removeItem:k=>storage.removeItem(prefix+k),get length(){return Object.keys(storage).filter(k=>k.startsWith(prefix)).length;},key:i=>Object.keys(storage).filter(k=>k.startsWith(prefix))[i]?.slice(prefix.length)}});
const matchMedia=window.matchMedia.bind(window);window.matchMedia=query=>query.includes('prefers-reduced-motion')?{matches:reduced,addEventListener(){},removeEventListener(){}}:matchMedia(query);
const qa=document.createElement('details');qa.id='values-qa';qa.innerHTML='<summary>Values QA</summary><label>Fixture<select id="fixture"><option>Hack Squat</option><option>Matching</option><option>Manual RIR</option><option>Per side</option><option>Bodyweight</option><option>Assisted</option><option>Timed</option><option>lb RIR off</option></select></label><label>Theme<select id="theme"><option>premium-dark</option><option>premium-light</option><option>dark</option><option>light</option></select></label><button id="reset">Reset fixture</button><button id="measure">Measure</button><button id="failure">Toggle save failure</button><button id="reduced">Toggle reduced motion</button><button id="scroll">Scroll to helper</button><a href="?resume=1">Reload saved session</a><pre id="proof"></pre>';
const css=document.createElement('style');css.textContent='#values-qa{position:fixed;right:0;top:0;z-index:9999;width:120px;font:10px system-ui;background:#eee;color:#111}#values-qa label,#values-qa button{display:block;width:100%;min-height:28px}#values-qa select{max-width:120px}#proof{white-space:pre-wrap;max-height:100px;overflow:auto}';document.head.append(css);document.body.append(qa);
const el=id=>qa.querySelector('#'+id),root=createRoot(document.getElementById('root')),releaseFocus=bindNavigationFocus(),releaseViewport=observeVisibleViewport(),samples=[];
function seed(){const fixture=el('fixture').value,id=fixture==='Bodyweight'?'pull-up':fixture==='Assisted'?'assisted-pull-up':fixture==='Timed'?'plank':'hack-squat';let state=addFreestyleExercise(startFreestyleWorkout(createReturningUserFixture(0)),id);state=addFreestyleExercise(state,'leg-press');
 Object.assign(state.profile,{showExerciseImages:true,restTimerEnabled:true,rirEnabled:fixture!=='lb RIR off',units:fixture==='lb RIR off'?'lb':'kg',appearancePreference:'dark',stylePreference:'premium',themePreference:'premium'});
 const exercise=state.activeWorkout.exercises[0],first=exercise.sets[0];exercise.loggingMode=fixture==='Per side'?'per_side':'normal';
 exercise.sets=Array.from({length:3},(_,i)=>({...structuredClone(first),id:first.id+'-'+i,...(fixture==='Per side'?{sides:{left:{reps:null},right:{reps:null}}}:{})}));
 if(fixture==='Matching')Object.assign(exercise.sets[0],{weight:90,reps:7});
 if(fixture==='Manual RIR')Object.assign(exercise.sets[0],{weight:52.5,reps:10,rir:3,touched:true});
 state.workouts=[{id:'previous',completedAt:new Date(Date.now()-86400000).toISOString(),exercises:[{...structuredClone(exercise),sets:[{weight:id==='plank'||id==='pull-up'?null:90,reps:id==='plank'?45:7,rir:2,completed:true,...(fixture==='Per side'?{sides:{left:{reps:7},right:{reps:9}}}:{})}]}]}];
 state.activeWorkout.startedAt-=120000;state.activeWorkout.rest={endsAt:Date.now()+900000,seconds:900};failWrites=false;saveState(state);samples.length=0;
}
const mount=()=>root.render(<StrictMode key={++revision}><App/></StrictMode>);
if(!params.has('resume'))seed();mount();
el('theme').onchange=()=>{const value=el('theme').value;Object.assign(document.documentElement.dataset,{theme:value.startsWith('premium')?'premium':value,style:value.startsWith('premium')?'premium':'standard',appearance:value.endsWith('dark')?'dark':'light',premiumScheme:value.endsWith('dark')?'dark':'light'});};
const box=node=>{if(!node)return null;const r=node.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};};
const measure=()=>({width:innerWidth,theme:el('theme').value,reduced,writes,failWrites,helper:box(document.querySelector('.freestyle-copy-helper')),history:box(document.querySelector('.freestyle-history-aid')),rows:[...document.querySelectorAll('[data-set-id]')].map(node=>({id:node.dataset.setId,...box(node),controls:[...node.querySelectorAll('button,input')].map(c=>({label:c.getAttribute('aria-label')||c.textContent,value:c.value,disabled:c.disabled,...box(c)}))})),scroll:document.scrollingElement.scrollTop,overflow:document.documentElement.scrollWidth>innerWidth,session:loadState().activeWorkout,samples});
const probe=event=>{const button=event.target.closest('button');if(!button?.matches('.freestyle-copy,.freestyle-copy-applied button'))return;const row=document.querySelector('[data-set-id]'),weight=row?.querySelector('input'),start=performance.now(),sample={action:button.textContent,before:box(document.querySelector('.freestyle-copy-helper')),scrollBefore:document.scrollingElement.scrollTop,frames:[]};samples.push(sample);
 const frame=()=>{sample.frames.push({ms:performance.now()-start,height:document.querySelector('.freestyle-copy-helper')?.getBoundingClientRect().height,row:box(row),scroll:document.scrollingElement.scrollTop,sameInput:weight===row?.querySelector('input'),animations:document.getAnimations().filter(a=>a.effect?.target?.closest('.freestyle-copy-helper')||a.effect?.target?.matches('[data-workout-draft]')).map(a=>({target:a.effect.target.className,duration:a.effect.getTiming().duration,frames:a.effect.getKeyframes()}))});if(performance.now()-start<260)requestAnimationFrame(frame);};requestAnimationFrame(frame);
};document.addEventListener('click',probe,true);
el('measure').onclick=()=>{el('proof').textContent=JSON.stringify(measure());qa.open=false;};
el('reset').onclick=()=>{qa.open=false;root.render(null);seed();mount();};
el('failure').onclick=()=>{failWrites=!failWrites;el('proof').textContent=JSON.stringify({failWrites});qa.open=false;};
el('reduced').onclick=()=>{reduced=!reduced;el('proof').textContent=JSON.stringify({reduced});qa.open=false;};
el('scroll').onclick=()=>{const aid=document.querySelector('.freestyle-history-aid');if(aid)document.scrollingElement.scrollTop+=aid.getBoundingClientRect().top-120;qa.open=false;};
if(import.meta.hot)import.meta.hot.dispose(()=>{root.unmount();releaseFocus();releaseViewport();qa.remove();css.remove();document.removeEventListener('click',probe,true);window.matchMedia=matchMedia;Object.defineProperty(window,'localStorage',{configurable:true,value:storage});});
