import { chromium } from 'playwright-core';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createReturningUserFixture } from '../src/demoFixture.js';
import { buildProgram } from '../src/domain.js';

const target = new URL('../artifacts/visual-v2/', import.meta.url); await mkdir(target, { recursive: true }); const output = name => fileURLToPath(new URL(name, target));
const browser = await chromium.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true });
async function snap(page, name, width) { await page.setViewportSize({ width, height: 844 }); await page.screenshot({ path: output(`${width}-${name}.png`), fullPage: false }); }
async function selectIfNeeded(page, name) { const button = page.getByRole('button', { name, exact: true }); if (await button.getAttribute('aria-pressed') !== 'true') await button.click(); }

const freshContext = await browser.newContext({ viewport: { width: 375, height: 844 }, serviceWorkers: 'block' }); const fresh = await freshContext.newPage(); await fresh.route('**/api/ai/status', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ available: true, provider: 'visual-qa' }) })); await fresh.route('**/api/ai', async route => { const body = route.request().postDataJSON(); if (body.operation === 'follow-ups') return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ data: { questions: [] } }) }); if (body.operation === 'plan') { const generated = buildProgram(body.payload.profile); const data = { name: generated.name, days: generated.days.map(day => ({ weekday: day.weekday, location: day.location, name: day.name, estimatedMinutes: day.estimatedMinutes, exercises: day.exercises.map(exercise => ({ exerciseId: exercise.exerciseId, sets: exercise.sets.length, repMin: exercise.repMin, repMax: exercise.repMax, targetRir: exercise.targetRir, restSeconds: exercise.restSeconds })) })) }; return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ data }) }); } return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Unexpected visual QA operation.' }) }); }); await fresh.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' }); await snap(fresh, 'fresh-onboarding', 375);
await fresh.getByRole('button', { name: 'BUILD MY PLAN' }).click();
await fresh.getByRole('combobox', { name: 'Age range' }).selectOption('30–39');
await fresh.getByRole('button', { name: 'CONTINUE' }).click();
await fresh.getByRole('button', { name: 'Build muscle' }).click(); await fresh.getByRole('button', { name: 'CONTINUE' }).click();
await fresh.getByRole('button', { name: 'Beginner' }).click(); await fresh.getByRole('button', { name: 'CONTINUE' }).click();
await selectIfNeeded(fresh, '3 days');
for (const day of ['Mon', 'Wed', 'Fri']) await selectIfNeeded(fresh, day);
await selectIfNeeded(fresh, '60 min'); await fresh.getByRole('button', { name: 'CONTINUE' }).click();
await fresh.getByRole('button', { name: 'Commercial gym' }).click(); await fresh.getByRole('button', { name: 'CONTINUE' }).click();
await fresh.getByRole('button', { name: 'Balanced' }).click(); await fresh.getByRole('button', { name: 'CONTINUE' }).click();
await fresh.getByRole('button', { name: /Balanced starting point/ }).click(); await fresh.getByRole('button', { name: 'CONTINUE' }).click();
await fresh.getByRole('button', { name: 'BUILD MY PLAN' }).click(); await fresh.getByRole('heading', { name: 'Your week is ready.' }).waitFor(); await fresh.getByRole('button', { name: 'USE THIS PLAN' }).click(); await fresh.waitForFunction(() => Boolean(JSON.parse(localStorage.getItem('lift-v2-state'))?.profile?.onboardingComplete));
const firstPlannedDay = await fresh.evaluate(() => JSON.parse(localStorage.getItem('lift-v2-state')).program.days[0].weekday); await fresh.getByRole('button', { name: new RegExp(`^${firstPlannedDay} `) }).click(); await fresh.getByRole('button', { name: 'START WORKOUT' }).waitFor();
for (const width of [375, 390, 430, 500]) await snap(fresh, 'fresh-today', width); await fresh.getByRole('button', { name: 'START WORKOUT' }).click(); await snap(fresh, 'fresh-active', 390); await fresh.getByRole('button', { name: 'Back to Today' }).click(); await fresh.getByRole('button', { name: 'COACH', exact: true }).click(); await snap(fresh, 'fresh-coach', 430); await fresh.getByRole('button', { name: 'PROGRESS', exact: true }).click(); await snap(fresh, 'fresh-progress', 375); await fresh.getByRole('button', { name: 'PROFILE', exact: true }).click(); await snap(fresh, 'fresh-profile', 500); await freshContext.close();

const returningContext = await browser.newContext({ viewport: { width: 390, height: 844 } }); await returningContext.addInitScript(state => localStorage.setItem('lift-v2-state', JSON.stringify(state)), createReturningUserFixture(6)); const returning = await returningContext.newPage(); await returning.route('**/api/ai/status', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ available: false, provider: null }) })); await returning.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' }); await snap(returning, 'returning-today', 390); await returning.getByRole('button', { name: 'START WORKOUT' }).click(); await snap(returning, 'returning-active', 375); await returning.getByRole('button', { name: 'Replace ›' }).click(); await snap(returning, 'returning-replace', 430); await returning.getByRole('button', { name: 'Close', exact: true }).click(); await returning.getByRole('button', { name: 'Back to Today' }).click(); await returning.getByRole('button', { name: 'PROGRESS', exact: true }).click(); await snap(returning, 'returning-progress', 430); await returning.locator('.progress-screen .list-row').first().click(); await snap(returning, 'returning-exercise-detail', 390); await returning.getByRole('button', { name: 'Close', exact: true }).click(); await returning.getByRole('button', { name: 'COACH', exact: true }).click(); await returning.getByRole('button', { name: 'Adapt today to 35 minutes.' }).click(); await returning.getByRole('button', { name: 'APPLY TO TODAY' }).waitFor(); await returning.getByRole('button', { name: 'APPLY TO TODAY' }).scrollIntoViewIfNeeded(); await snap(returning, 'returning-coach-adapt', 500); await returning.getByRole('button', { name: 'PROFILE', exact: true }).click(); await snap(returning, 'returning-profile', 375); await browser.close();
