import React,{StrictMode} from 'react';
import {createRoot} from 'react-dom/client';
import App from '/src/App.jsx';
import {createReturningUserFixture} from '/src/demoFixture.js';
import {startWorkout,saveState,loadState} from '/src/domain.js';
import {startFreestyleWorkout,addFreestyleExercise} from '/src/freestyleWorkout.js';
import {repeatedRestartFixture} from '/src/restartWorkout.fixture.js';
import {bindNavigationFocus} from '/src/navigationFocus.js';
import {observeVisibleViewport} from '/src/sheetVisibleViewport.js';
import '/src/styles.css';import '/src/overrides.css';import '/src/overlay.css';import '/src/calendar.css';import '/src/workout-controls.css';import '/src/onboarding-controls.css';import '/src/import-plan.css';import '/src/coach.css';import '/src/landing.css';import '/src/theme.css';import '/src/navigationFocus.css';import '/src/activeLoggerTouch.css';
if(!import.meta.env.DEV||location.origin!=='http://127.0.0.1:4198')throw Error('Isolated review only');
const storage=window.localStorage,prefix='rook-workout-options:',params=new URLSearchParams(location.search);let writes=0,failWrites=false,revision=0;
Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>storage.getItem(prefix+k),setItem:(k,v)=>{if(failWrites)throw Error('Review storage failure');writes++;storage.setItem(prefix+k,v);},removeItem:k=>storage.removeItem(prefix+k),get length(){return Object.keys(storage).filter(k=>k.startsWith(prefix)).length;},key:i=>Object.keys(storage).filter(k=>k.startsWith(prefix))[i]?.slice(prefix.length)}});
const qa=document.createElement('details');qa.id='options-qa';qa.innerHTML='<summary>Options QA</summary><label>Fixture<select id="fixture"><option>UPPER A</option><option>Upper Strength and Hypertrophy A</option><option>Freestyle workout</option><option>Repeated leg workout</option></select></label><label>Theme<select id="theme"><option>premium-dark</option><option>premium-light</option><option>dark</option><option>light</option></select></label><button id="reset">Reset fixture</button><button id="measure">Measure</button><button id="touch">Touch open</button><button id="failure">Toggle save failure</button><button id="cycles">Ten open-close cycles</button><pre id="proof"></pre>';
const css=document.createElement('style');css.textContent='#options-qa{position:fixed;right:0;bottom:0;z-index:9999;width:150px;font:11px system-ui;background:#eee;color:#111}#options-qa label,#options-qa button{display:block;width:100%;min-height:28px}#options-qa select{max-width:150px}#proof{white-space:pre-wrap;max-height:100px;overflow:auto}';document.head.append(css);document.body.append(qa);
const el=id=>qa.querySelector('#'+id),root=createRoot(document.getElementById('root')),releaseFocus=bindNavigationFocus(),releaseViewport=observeVisibleViewport();
if(params.has('fixture'))el('fixture').value=params.get('fixture');
function seed(){let state=el('fixture').value==='Repeated leg workout'?repeatedRestartFixture({legacySnapshot:true}):createReturningUserFixture(0);state.profile.showExerciseImages=false;state.profile.restTimerEnabled=true;state.profile.appearancePreference='dark';state.profile.stylePreference='premium';state.profile.themePreference='premium';
 if(el('fixture').value==='Freestyle workout'){state=startFreestyleWorkout(state);for(const id of ['barbell-bench-press','cable-fly','barbell-row','plank'])state=addFreestyleExercise(state,id);}
 else if(el('fixture').value!=='Repeated leg workout')state.activeWorkout=startWorkout(state,{...state.program.days[0],name:el('fixture').value});
 state.activeWorkout.startedAt-=120000;if(el('fixture').value==='Repeated leg workout')state.activeWorkout.exerciseIndex=1;Object.assign(state.activeWorkout.exercises[0].sets[0],{weight:52.5,reps:10,rir:2,touched:true,completed:true,completedAt:Date.now()-10000});state.activeWorkout.rest={endsAt:Date.now()+90000,seconds:90};failWrites=false;saveState(state);return state;
}
const mount=()=>root.render(<StrictMode key={++revision}><App/></StrictMode>);
if(!params.has('resume'))seed();mount();
const theme=()=>{const value=el('theme').value;Object.assign(document.documentElement.dataset,{theme:value.startsWith('premium')?'premium':value,style:value.startsWith('premium')?'premium':'standard',appearance:value.endsWith('dark')?'dark':'light',premiumScheme:value.endsWith('dark')?'dark':'light'});};el('theme').onchange=theme;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),out=v=>el('proof').textContent=JSON.stringify(v),panel=()=>document.querySelector('.active-workout-options-sheet');
const box=node=>{if(!node)return null;const r=node.getBoundingClientRect(),s=getComputedStyle(node);return {x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom,outline:s.outline,focusVisible:node.matches(':focus-visible'),pointerFocus:node.getAttribute('data-rook-pointer-focus'),background:s.backgroundColor,paddingBottom:s.paddingBottom,tapHighlight:s.webkitTapHighlightColor};};
function proof(){const state=loadState();return {width:innerWidth,theme:el('theme').value,fixture:el('fixture').value,header:box(document.querySelector('.workout-header')),title:box(document.querySelector('.workout-header-center')),finish:box(document.querySelector('.workout-header-actions .text-button')),trigger:box(document.querySelector('.workout-options-trigger')),close:box(document.querySelector('.sheet-close')),panel:box(panel()),scroll:box(panel()?.querySelector('.sheet-scroll')),actions:[...panel()?.querySelectorAll('.sheet-scroll button')||[]].map(b=>({text:b.textContent,disabled:b.disabled,...box(b)})),layers:document.querySelectorAll('.modal-layer').length,locked:document.body.style.position==='fixed',overflow:document.documentElement.scrollWidth>innerWidth,writes,failWrites,session:state.activeWorkout,historyCount:state.workouts.length};}
el('reset').onclick=()=>{qa.open=false;root.render(null);seed();mount();};
el('measure').onclick=()=>{out(proof());qa.open=false;};
el('failure').onclick=()=>{failWrites=!failWrites;out({failWrites});qa.open=false;};
el('touch').onclick=async()=>{qa.open=false;const b=document.querySelector('.workout-options-trigger');b.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerType:'touch',button:0}));b.focus();b.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerType:'touch',button:0}));b.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));await wait(300);out(proof());};
el('cycles').onclick=async()=>{qa.open=false;out({running:true});const timings=[];for(let i=0;i<10;i++){const t=performance.now();document.querySelector('.workout-options-trigger').click();await new Promise(requestAnimationFrame);timings.push(performance.now()-t);await wait(240);panel().querySelector('.sheet-close').click();await wait(280);}out({...proof(),timings});};
if(import.meta.hot)import.meta.hot.dispose(()=>{root.unmount();releaseFocus();releaseViewport();qa.remove();css.remove();Object.defineProperty(window,'localStorage',{configurable:true,value:storage});});
