import React,{act,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {ActiveWorkout,Today} from './App.jsx';
import {useSemanticSwipeBack} from './useSemanticSwipeBack.js';
import {rememberSwipeParent} from './swipePageMotion.js';
import {createReturningUserFixture} from './demoFixture.js';
import {startWorkout,isoDay,serializeState,deserializeState} from './domain.js';
let root,host,current,navigations,writes,finish,width=390,reduced=false,standalone=true;
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-09-18T12:00:00'));width=390;reduced=false;standalone=true;vi.stubGlobal('matchMedia',q=>({matches:q.includes('standalone')?standalone:q.includes('reduced-motion')?reduced:false,addEventListener(){},removeEventListener(){}}));vi.stubGlobal('requestAnimationFrame',cb=>setTimeout(cb,0));vi.stubGlobal('cancelAnimationFrame',clearTimeout);vi.stubGlobal('scrollTo',()=>{});vi.spyOn(HTMLElement.prototype,'getClientRects').mockImplementation(function(){return this.closest('[hidden]')?[]:[{}];});vi.spyOn(HTMLElement.prototype,'getBoundingClientRect').mockImplementation(()=>({left:0,top:0,width,height:844,right:width,bottom:844}));HTMLElement.prototype.getAnimations=()=>[];HTMLElement.prototype.scrollTo=()=>{};host=document.createElement('div');document.body.append(host);root=createRoot(host);navigations=vi.fn();writes=vi.fn();finish=vi.fn();});
afterEach(()=>{act(()=>root.unmount());host.remove();vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals();});
function fixture(kind='weighted',index=0,rir=true){const s=createReturningUserFixture(0);Object.assign(s.profile,{rirEnabled:rir,showExerciseImages:false,restTimerEnabled:false});s.selectedDate=isoDay();const t=structuredClone(s.program.days[0]);t.exercises=t.exercises.slice(0,3);t.exercises.forEach((e,i)=>{e.exerciseId=(kind==='timed'?['plank','side-plank','bosu-balance']:kind==='bodyweight'?['push-up','pull-up','chin-up']:kind==='per-side'?['split-squat','bulgarian-split-squat','step-up']:['barbell-bench-press','dumbbell-bench-press','incline-dumbbell-press'])[i];e.loggingMode=kind==='per-side'?'per_side':'normal';});s.activeWorkout=startWorkout(s,t);s.activeWorkout.startedAt=Date.now()-185000;s.activeWorkout.exerciseIndex=index;s.activeWorkout.exercises.forEach(e=>e.sets.forEach((set,i)=>{Object.assign(set,{weight:kind==='bodyweight'||kind==='timed'?null:52.5,reps:kind==='timed'?30:12,rir:rir?2:null,completed:i===0});if(kind==='per-side')set.sides={left:{reps:11,completed:i===0},right:{reps:12,completed:i===0}};}));return s;}
function mount(s){function Harness(){useSemanticSwipeBack();const [state,setState]=useState(s),[page,setPageState]=useState('workout'),[overlay,setOverlay]=useState(false);current=state;const setPage=p=>{navigations(p);if(p==='workout')rememberSwipeParent(document.querySelector('.today-screen'),'workout');setPageState(p);};const update=fn=>setState(prev=>{const next=fn(structuredClone(prev));writes(next);return next;});return <>{page==='workout'?<ActiveWorkout state={state} update={update} setPage={setPage} setDetail={()=>setOverlay(true)} onLiveFinish={finish}/>:<Today state={state} update={update} setPage={setPage} setDetail={()=>{}}/>}{overlay&&<aside role="dialog" aria-modal="true"><button onClick={()=>setOverlay(false)}>Close overlay</button></aside>}</>;}act(()=>root.render(<Harness/>));}
const main=()=>host.querySelector('[data-active-workout]');
function touch(type,x,y=200,target=main()){const e=new Event(type,{bubbles:true,cancelable:true});Object.defineProperty(e,'touches',{value:type==='touchend'||type==='touchcancel'?[]:[{identifier:0,clientX:x,clientY:y}]});act(()=>target.dispatchEvent(e));return e;}
function swipe({start=4,end=width*.6,y=200,target=main(),cancel=false}={}){touch('touchstart',start,200,target);touch('touchmove',end,y,target);act(()=>vi.advanceTimersByTime(120));touch(cancel?'touchcancel':'touchend',end,y,target);act(()=>vi.advanceTimersByTime(220));}
function type(el,value){act(()=>el.focus());act(()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});}
const cases=['weighted','bodyweight','timed','per-side'].flatMap(kind=>[0,1,2].flatMap(index=>[false,true].flatMap(rir=>[320,390,430].map(w=>[kind,index,rir,w]))));
it.each(cases)('Back/Resume preserves %s exercise %i RIR %s at %i px', (kind,index,rir,w)=>{width=w;mount(fixture(kind,index,rir));const input=[...main().querySelectorAll('input[data-workout-draft]')].find(i=>!i.disabled);type(input,input.value);const expected=structuredClone(current.activeWorkout),oldHistory=structuredClone(current.workouts),beforeWrites=writes.mock.calls.length,blur=vi.spyOn(input,'blur');swipe();expect(blur).toHaveBeenCalledOnce();expect(navigations.mock.calls).toEqual([['today']]);expect(main()).toBeNull();expect(current.activeWorkout).toEqual(expected);expect(current.workouts).toEqual(oldHistory);expect(writes).toHaveBeenCalledTimes(beforeWrites);expect(finish).not.toHaveBeenCalled();const resume=[...host.querySelectorAll('button')].find(b=>/RESUME WORKOUT/i.test(b.textContent));expect(resume).toBeDefined();act(()=>resume.click());expect(main()).not.toBeNull();expect(current.activeWorkout).toEqual(expected);expect(deserializeState(serializeState(current)).activeWorkout).toMatchObject({id:expected.id,startedAt:expected.startedAt,exerciseIndex:index});});
it('button and completed gesture use one Back path, normalize the focused raw draft, and do not double-commit',()=>{mount(fixture());const input=[...main().querySelectorAll('input[data-workout-draft]')].find(i=>!i.disabled);type(input,'53,');act(()=>input.blur());type(input,'53,');const expected=structuredClone(current.activeWorkout),calls=writes.mock.calls.length,blur=vi.spyOn(input,'blur');act(()=>main().querySelector('[aria-label="Back to Today"]').click());expect(blur).toHaveBeenCalledOnce();expect(navigations).toHaveBeenCalledExactlyOnceWith('today');expect(current.activeWorkout).toEqual(expected);expect(writes).toHaveBeenCalledTimes(calls);});
it.each(['short','cancel','vertical','center','browser','overlay'])('keeps live logger and focused draft for %s',reason=>{standalone=reason!=='browser';mount(fixture());const surface=main(),input=[...surface.querySelectorAll('input[data-workout-draft]')].find(i=>!i.disabled);type(input,'53,');const before=structuredClone(current.activeWorkout);surface.scrollTop=350;if(reason==='overlay'){const overlay=document.createElement('aside');overlay.setAttribute('role','dialog');host.append(overlay);}swipe({end:reason==='short'?38:240,start:reason==='center'?70:4,y:reason==='vertical'?440:200,cancel:reason==='cancel'});expect(navigations).not.toHaveBeenCalled();expect(main()).toBe(surface);expect(surface.scrollTop).toBe(350);expect(input.value).toBe('53,');expect(document.activeElement).toBe(input);expect(current.activeWorkout).toEqual(before);expect(surface.style.transform).toBe('');});
it.each(['button','input','.rir-trigger'])('never steals horizontal control gestures from %s, including at the edge',selector=>{mount(fixture());const target=main().querySelector(selector),before=structuredClone(current.activeWorkout);swipe({target});expect(navigations).not.toHaveBeenCalled();expect(current.activeWorkout).toEqual(before);});
it('an overlay opening during drag cancels page navigation',()=>{mount(fixture());touch('touchstart',4);touch('touchmove',180);const layer=document.createElement('aside');layer.setAttribute('role','dialog');host.append(layer);touch('touchend',180);act(()=>vi.advanceTimersByTime(250));expect(navigations).not.toHaveBeenCalled();expect(main().style.transform).toBe('');});
it('reduced motion uses the same destination without animated transforms',()=>{reduced=true;mount(fixture());touch('touchstart',4);touch('touchmove',220);expect(main().style.transform).toBe('');touch('touchend',220);expect(navigations).toHaveBeenCalledExactlyOnceWith('today');});
it('preserves independent edited sides, nullable load and RIR through focused Back',()=>{mount(fixture('per-side',1));const left=main().querySelector('[aria-label="left reps for set 2"]'),right=main().querySelector('[aria-label="right reps for set 2"]');type(left,'17');type(right,'21');const rir=main().querySelector('[aria-label="RIR for set 2"]');act(()=>right.blur());act(()=>rir.click());act(()=>[...document.querySelectorAll('.rir-options button')].find(b=>b.getAttribute('aria-label')==='3 RIR').click());act(()=>vi.advanceTimersByTime(400));type(right,'21');const expected=structuredClone(current.activeWorkout),set=expected.exercises[1].sets[1];expect(set.sides.left.reps).toBe(17);expect(set.sides.right.reps).toBe(21);expect(set.rir).toBe(3);swipe();expect(current.activeWorkout).toEqual(expected);});
it.each(['Decrease Weight in kg for set 2','Increase Weight in kg for set 2','Decrease Reps for set 2','Increase Reps for set 2','RIR for set 2','Log set 2'])('control owns its horizontal gesture: %s',label=>{mount(fixture());const target=main().querySelector(`[aria-label="${label}"]`),before=structuredClone(current.activeWorkout);expect(target).not.toBeNull();swipe({target});expect(navigations).not.toHaveBeenCalled();expect(current.activeWorkout).toEqual(before);if(label==='Increase Weight in kg for set 2'){act(()=>target.click());expect(current.activeWorkout.exercises[0].sets[1].weight).toBeGreaterThan(before.exercises[0].sets[1].weight);}if(label==='Log set 2'){act(()=>target.click());expect(current.activeWorkout.exercises[0].sets[1].completed).toBe(true);}});
it('real finish confirmation keeps page Back unavailable until dismissed',()=>{mount(fixture());act(()=>[...main().querySelectorAll('button')].find(b=>b.textContent==='Finish').click());expect(document.querySelector('[role="dialog"]')).not.toBeNull();swipe();expect(navigations).not.toHaveBeenCalled();act(()=>[...document.querySelectorAll('button')].find(b=>b.textContent==='KEEP TRAINING').click());act(()=>vi.advanceTimersByTime(220));swipe();expect(navigations).toHaveBeenCalledExactlyOnceWith('today');expect(finish).not.toHaveBeenCalled();});
it('visible contextual overlays also retain gesture ownership',()=>{mount(fixture());const tooltip=document.createElement('aside');tooltip.setAttribute('role','tooltip');host.append(tooltip);swipe();expect(navigations).not.toHaveBeenCalled();});
it('valid focused draft commits exactly once before edge Back and Resume',()=>{mount(fixture());const input=main().querySelector('[aria-label="Weight in kg for set 2"]'),before=structuredClone(current.activeWorkout);type(input,'142,5');expect(current.activeWorkout).toEqual(before);writes.mockClear();swipe();expect(navigations).toHaveBeenCalledExactlyOnceWith('today');expect(writes).toHaveBeenCalledOnce();const after=structuredClone(current.activeWorkout);expect(after.id).toBe(before.id);expect(after.startedAt).toBe(before.startedAt);expect(after.exercises[0].sets[1].weight).toBe(142.5);act(()=>[...host.querySelectorAll('button')].find(b=>/RESUME WORKOUT/i.test(b.textContent)).click());expect(current.activeWorkout).toEqual(after);});
it('invalid draft blocks completed Back and remains editable, without logging old canonical values',()=>{mount(fixture());const input=main().querySelector('[aria-label="Reps for set 2"]');type(input,'');swipe();expect(navigations).not.toHaveBeenCalled();expect(input.value).toBe('');expect(input.getAttribute('aria-invalid')).toBe('true');act(()=>main().querySelector('[aria-label="Log set 2"]').click());expect(current.activeWorkout.exercises[0].sets[1].completed).toBe(false);expect(input.value).toBe('');});
it('edit then Done commits once and logs once; future rows keep their identity',()=>{mount(fixture());const input=main().querySelector('[aria-label="Weight in kg for set 2"]'),future=main().querySelector('[aria-label="Weight in kg for set 3"]');type(input,'142.5');writes.mockClear();act(()=>main().querySelector('[aria-label="Log set 2"]').click());expect(current.activeWorkout.exercises[0].sets[1]).toMatchObject({weight:142.5,completed:true});expect(writes).toHaveBeenCalledTimes(2);expect(main().querySelector('[aria-label="Weight in kg for set 3"]')).toBe(future);act(()=>input.blur());expect(writes).toHaveBeenCalledTimes(2);});
it('edit then RIR opens one managed dialog and commits once; page Back is blocked',()=>{mount(fixture());const input=main().querySelector('[aria-label="Weight in kg for set 2"]');type(input,'142,5');writes.mockClear();act(()=>main().querySelector('[aria-label="RIR for set 2"]').click());expect(writes).toHaveBeenCalledOnce();expect(current.activeWorkout.exercises[0].sets[1].weight).toBe(142.5);expect(document.querySelectorAll('[role="dialog"]')).toHaveLength(1);swipe();expect(navigations).not.toHaveBeenCalled();});
it('RIR preference off, serialized reload, on preserves the complete active workout',()=>{const s=fixture(),before=structuredClone(s.activeWorkout);s.profile.rirEnabled=false;const restored=deserializeState(serializeState(s));expect(restored.activeWorkout.exercises[0].sets[1].rir).toBe(2);restored.profile.rirEnabled=true;mount(restored);expect(current.activeWorkout.id).toBe(before.id);expect(current.activeWorkout.exercises.map(e=>e.id)).toEqual(before.exercises.map(e=>e.id));expect(current.activeWorkout.exercises[0].sets.map(s=>[s.weight,s.reps,s.rir,s.completed])).toEqual(before.exercises[0].sets.map(s=>[s.weight,s.reps,s.rir,s.completed]));expect(main().querySelector('[aria-label="RIR for set 2"]').textContent).toContain('2');});
it.each([null,0,2,4])('RIR sheet preserves explicit %s semantics and the same logger nodes',value=>{const s=fixture();s.activeWorkout.exercises[0].sets[1].rir=value;mount(s);const surface=main(),input=surface.querySelector('[aria-label="Weight in kg for set 2"]'),trigger=surface.querySelector('[aria-label="RIR for set 2"]');surface.scrollTop=200;act(()=>{trigger.focus();trigger.click();});expect(document.querySelector('.rir-sheet')).not.toBeNull();const name=value===null?'Not set':`${value} RIR`,option=document.querySelector(`.rir-options [aria-label="${name}"]`);expect(option.getAttribute('aria-pressed')).toBe('true');act(()=>option.click());act(()=>vi.advanceTimersByTime(250));act(()=>vi.advanceTimersByTime(1));expect(current.activeWorkout.exercises[0].sets[1].rir).toBe(value);expect(main()).toBe(surface);expect(main().querySelector('[aria-label="Weight in kg for set 2"]')).toBe(input);expect(surface.scrollTop).toBe(200);expect(document.activeElement).toBe(trigger);});
it('provenance does not compete on the execution surface and its source text is retained',()=>{const s=fixture(),source='Bench Press 3x9 155 kg / machine press 3x8 173 kg';s.program.importMetadata={sourceNotes:[{text:source}]};s.activeWorkout.exercises[0].notes=source;mount(s);expect(main().querySelector('.exercise-source-link')).toBeNull();expect(current.activeWorkout.exercises[0].notes).toBe(source);expect(current.program.importMetadata.sourceNotes[0].text).toBe(source);});
it('pending completion differs from logged state and RIR help is a named heading button',()=>{mount(fixture());const pending=main().querySelector('[aria-label="Log set 3"]');expect(pending.disabled).toBe(true);expect(pending.getAttribute('aria-pressed')).toBe('false');expect(pending.querySelector('.check-mark svg path')).not.toBeNull();expect(main().querySelector('[aria-label="Undo logged set 1"]').getAttribute('aria-pressed')).toBe('true');const help=main().querySelector('[aria-label="What is RIR?"]');expect(help.textContent).toContain('RIR');act(()=>help.click());expect(document.querySelector('[role="tooltip"]').textContent).toContain('How many clean reps');});
it('Final C future row keeps its independent pre-edit and all numeric actions through completion',()=>{mount(fixture());const row=main().querySelector('[aria-label="set 3"]'),input=row.querySelector('[aria-label="Weight in kg for set 3"]'),done=row.querySelector('[aria-label="Log set 3"]');expect(row.querySelectorAll('.stepper button')).toHaveLength(4);expect(done.disabled).toBe(true);type(input,'145');act(()=>row.querySelector('[aria-label="Decrease Weight in kg for set 3"]').click());act(()=>input.blur());const expected=current.activeWorkout.exercises[0].sets[2].weight;expect(expected).toBeLessThan(145);act(()=>main().querySelector('[aria-label="Log set 2"]').click());expect(current.activeWorkout.exercises[0].sets[2].weight).toBe(expected);expect(main().querySelector('[aria-label="set 3"]')).toBe(row);expect(main().querySelector('[aria-label="Weight in kg for set 3"]')).toBe(input);expect(done.disabled).toBe(false);expect(row.getAttribute('aria-current')).toBe('step');});
it('Final C retains independent per-side steps, direct edits and manual carry-forward protection',()=>{mount(fixture('per-side'));const left=main().querySelector('[aria-label="left reps for set 2"]'),right=main().querySelector('[aria-label="right reps for set 2"]');type(left,'17');act(()=>main().querySelector('[aria-label="Increase left reps for set 2"]').click());act(()=>left.blur());expect(current.activeWorkout.exercises[0].sets[1].sides.left.reps).toBe(18);expect(current.activeWorkout.exercises[0].sets[1].sides.right.reps).toBe(12);const future=main().querySelector('[aria-label="right reps for set 3"]');type(future,'21');act(()=>future.blur());type(right,'14');act(()=>main().querySelector('[aria-label="Log set 2"]').click());expect(current.activeWorkout.exercises[0].sets[1].sides).toMatchObject({left:{reps:18},right:{reps:14}});expect(current.activeWorkout.exercises[0].sets[2].sides.right.reps).toBe(21);expect(main().querySelector('[aria-label="right reps for set 3"]')).toBe(future);});
it('Final C unset required and optional loads retain their native button structure and rules',()=>{const s=fixture();s.activeWorkout.exercises[0].sets[2].weight=null;mount(s);const input=main().querySelector('[aria-label="Weight in kg for set 3"]'),stepper=input.closest('.stepper');expect(stepper.querySelectorAll('button')).toHaveLength(2);expect([...stepper.querySelectorAll('button')].every(b=>b.disabled)).toBe(true);type(input,'155');act(()=>input.blur());expect([...stepper.querySelectorAll('button')].every(b=>!b.disabled)).toBe(true);expect(main().querySelector('[aria-label="Weight in kg for set 3"]')).toBe(input);});
