import { describe,it,expect,vi,afterEach } from 'vitest';
import { blankState,buildProgram,deserializeState,startWorkout,completeWorkout,isoDay,coachContext,exerciseCatalog } from './domain.js';
import { prescribeTrainingBlockWorkout,advanceTrainingBlockAfterWorkout,resolveTrainingBlockSkips } from './trainingBlocks.js';
import { normalizePlanHistoryState } from './planHistory.js';
import { normalizeGymProfilesState } from './gymProfiles.js';
import { buildBackupArchive,parseBackupArchive } from './backup.js';
import { createCustomExercise } from './customExercises.js';
import { applyNextBlock,proposeNextBlock,reviewTrainingBlock,nextBlockReplacementChoices } from './blockReview.js';
afterEach(()=>{vi.useRealTimers();});
export function completedBlockFixture({lowData=false}={}) {
 const s=blankState();Object.assign(s.profile,{goal:'Build muscle',experience:'Intermediate',daysPerWeek:3,availableDays:['Mon','Wed','Fri'],sessionMinutes:60,environment:'Commercial gym',equipment:['full gym'],priorities:['Balanced'],onboardingComplete:true,rirEnabled:true});
 s.program=buildProgram(s.profile);s.program.trainingBlock.startDate='2026-07-27';normalizeGymProfilesState(s);normalizePlanHistoryState(s,'2026-07-27T08:00:00Z');
 const b=s.program.trainingBlock;
 for(const week of b.weeks){b.currentWeek=week.weekNumber;for(const [index,day] of s.program.days.entries()){
  const w=prescribeTrainingBlockWorkout(s,day),date=new Date('2026-07-27T12:00:00Z');date.setUTCDate(date.getUTCDate()+(week.weekNumber-1)*7+index*2);
  s.workouts.push({...w,id:`history-${week.weekNumber}-${index}`,programDayId:day.id,completedAt:date.toISOString(),canonicalPlanDate:date.toISOString().slice(0,10),sourcePlanSlotId:w.trainingBlock.blockWorkoutId,exercises:w.exercises.map(e=>({...e,sets:e.sets.map(set=>({...set,weight:60,reps:e.repMax,rir:e.targetRir,planned:true,completed:!lowData || week.weekNumber===1}))})),endedEarly:lowData&&week.weekNumber!==1});
 }}
 advanceTrainingBlockAfterWorkout(s,s.workouts.at(-1));s.selectedDate=isoDay();return s;
}
describe('Block review evidence',()=>{
 it('empty history has no PR highlights',()=>{const s=completedBlockFixture();s.workouts=[];expect(reviewTrainingBlock(s).prs).toBe(0);});
 it('multiple PR types remain one quiet highlight per exercise and session',()=>{const s=completedBlockFixture(),r=reviewTrainingBlock(s);expect(r.prs).toBeGreaterThan(0);expect(r.prs).toBeLessThanOrEqual(s.workouts.reduce((n,w)=>n+w.exercises.length,0));});
 for(const kind of ['reps','weight','held','review'])it(`classifies comparable ${kind} evidence`,()=>{
  const s=completedBlockFixture(),day=s.program.days[0],base=day.exercises[0],sessions=s.workouts.filter(w=>w.programDayId===day.id&&!w.trainingBlock.plannedDeload);
  sessions.forEach((w,i)=>{const e=w.exercises.find(e=>e.id===base.id);Object.assign(e,{repMin:6,repMax:12,targetRir:1});e.sets=e.sets.slice(0,2).map(set=>({...set,reps:kind==='review'?4:kind==='reps'&&i===1?9:8,weight:kind==='weight'&&i===1?62:60,rir:1}));if(i>=2)w.adjustment={mode:'less-time'};});
  const row=reviewTrainingBlock(s).rows.find(r=>r.id===base.id);expect(row.status).toBe(kind==='reps'||kind==='weight'?'progressed':kind);
 });
 it('high-rep work is not presented as an estimated 1RM',()=>{const s=completedBlockFixture();for(const w of s.workouts)for(const e of w.exercises)for(const set of e.sets)set.reps=25;expect(reviewTrainingBlock(s).rows.every(row=>row.estimatedOneRepMax==null)).toBe(true);});
 it('a completed logical session is not also counted as skipped',()=>{const s=completedBlockFixture();s.program.trainingBlock.resolvedSkips=[{blockWorkoutId:s.workouts[0].trainingBlock.blockWorkoutId}];expect(reviewTrainingBlock(s).skipped).toBe(0);});
 it('one bad exposure does not become repeated-stall evidence',()=>{const s=completedBlockFixture();const last=s.workouts.filter(w=>!w.trainingBlock.plannedDeload).at(-1);for(const e of last.exercises)for(const set of e.sets)set.reps=1;expect(reviewTrainingBlock(s).rows.some(row=>row.status==='review')).toBe(false);});
 it('counts complete logical work, accepted working prescriptions and preserves history',()=>{
  const s=completedBlockFixture(),before=JSON.stringify(s),r=reviewTrainingBlock(s);expect(r.completedSessions).toBe(18);expect(r.plannedSessions).toBe(18);expect(r.loggedSets).toBe(r.prescribedSets);expect(r.deloadCompleted).toBe(true);expect(JSON.stringify(s)).toBe(before);
 });
 it('counts moved sessions once despite duplicate completion records',()=>{
  const s=completedBlockFixture();s.workouts[0].flexibleWeekMoved=true;s.workouts.push({...structuredClone(s.workouts[0]),id:'duplicate',completedAt:'2026-09-07T12:00:00Z'});const r=reviewTrainingBlock(s);expect(r.completedSessions).toBe(18);expect(r.moved).toBe(1);
 });
 it('excludes superseded completions',()=>{const s=completedBlockFixture(),w=s.workouts[0];s.workouts.push({...structuredClone(w),id:'correction',supersedesCompletionId:w.id});expect(reviewTrainingBlock(s).completedSessions).toBe(18);});
 it('removed Adjust Today sets are not missing prescribed work',()=>{const s=completedBlockFixture(),w=s.workouts[0];w.adjustment={mode:'less-time'};w.exercises[0].sets=w.exercises[0].sets.slice(0,1);const r=reviewTrainingBlock(s);expect(r.loggedSets).toBe(r.prescribedSets);expect(r.adjusted).toBe(1);});
 it('zero logged early finish is resolved but not counted as completed training',()=>{const s=completedBlockFixture({lowData:true}),r=reviewTrainingBlock(s);expect(r.completedSessions).toBe(3);expect(r.endedEarly).toBe(15);expect(r.rows.every(row=>row.status==='insufficient')).toBe(true);});
 it('optional work never inflates required sessions',()=>{const s=completedBlockFixture();s.workouts.push({...structuredClone(s.workouts[0]),id:'optional',optionalSessionId:'optional-1'});const r=reviewTrainingBlock(s);expect(r.completedSessions).toBe(18);expect(r.optionalCompleted).toBe(1);});
 it('deload does not trigger negative progression evidence',()=>{const s=completedBlockFixture();for(const w of s.workouts.filter(w=>w.trainingBlock.plannedDeload))for(const e of w.exercises)for(const set of e.sets){set.weight=5;set.reps=1;}const r=reviewTrainingBlock(s);expect(r.rows.some(row=>row.reason.includes('Two comparable sessions stayed below'))).toBe(false);});
 it('uses existing progression recommendations without automatically adding volume',()=>{const s=completedBlockFixture(),p=proposeNextBlock(s);expect(p.changes.some(c=>c.kind==='load')).toBe(true);expect(p.changes.every(c=>['load','replacement'].includes(c.kind))).toBe(true);expect(p.totalWeeks).toBe(6);expect(p.plannedDeloadWeek).toBe(6);});
 it('no meaningful evidence defaults to continuity',()=>{expect(proposeNextBlock(completedBlockFixture({lowData:true})).changes).toEqual([]);});
});
describe('Sequence completion',()=>{
 it('does not complete from a calendar end date',()=>{const s=completedBlockFixture();s.program.trainingBlock.completed=false;s.program.trainingBlock.currentWeek=1;s.workouts=[];expect(proposeNextBlock(s).status).toBe('unavailable');});
 it('final carried workout must finish before block completes',()=>{const s=completedBlockFixture(),last=s.workouts.pop();s.program.trainingBlock.completed=false;s.completedTrainingBlocks=[];advanceTrainingBlockAfterWorkout(s,s.workouts.at(-1));expect(s.program.trainingBlock.completed).toBe(false);last.flexibleWeekMoved=true;last.completedAt='2026-09-07T12:00:00Z';s.workouts.push(last);advanceTrainingBlockAfterWorkout(s,last);expect(s.program.trainingBlock.completed).toBe(true);});
 it('explicit final skip resolves without creating workout history',()=>{const s=completedBlockFixture(),last=s.workouts.pop(),b=s.program.trainingBlock;b.completed=false;s.completedTrainingBlocks=[];resolveTrainingBlockSkips(s,[{id:'skip',blockId:b.id,blockWeekNumber:6,workoutId:last.programDayId,skipped:true,originalDate:'2026-09-04'}]);expect(b.completed).toBe(true);expect(s.workouts).toHaveLength(17);expect(reviewTrainingBlock(s).skipped).toBe(1);});
 it('active final workout blocks advancement and application',()=>{const s=completedBlockFixture(),last=s.workouts.pop(),b=s.program.trainingBlock;b.completed=false;s.activeWorkout=last;resolveTrainingBlockSkips(s,[{id:'skip',blockId:b.id,blockWeekNumber:6,workoutId:last.programDayId,skipped:true}]);expect(b.completed).toBe(false);});
 it('optional completion cannot resolve a required obligation',()=>{const s=completedBlockFixture(),last=s.workouts.at(-1);last.optionalSessionId='optional';s.program.trainingBlock.completed=false;advanceTrainingBlockAfterWorkout(s,last);expect(s.program.trainingBlock.completed).toBe(false);});
});
describe('Review and atomic next block',()=>{
 it('a compatible custom replacement and transition round-trip through backup',async()=>{
  const s=completedBlockFixture(),day=s.program.days[0],e=day.exercises.find(e=>['horizontal-push','horizontal-pull','squat','hinge'].includes(exerciseCatalog[e.exerciseId]?.pattern)),match=nextBlockReplacementChoices(s,e)[0];
  const {exercise:custom}=createCustomExercise(s,{name:'My compatible gym station',equipment:match.equipment,primaryMuscle:match.muscles[0],secondaryMuscles:match.muscles.slice(1),pattern:match.pattern,loggingType:'weight_reps'});
  expect(nextBlockReplacementChoices(s,e).some(c=>c.id===custom.id)).toBe(true);
  for(const w of s.workouts.filter(w=>w.programDayId===day.id&&!w.trainingBlock.plannedDeload).slice(0,4))w.exercises.find(item=>item.id===e.id).exerciseId=custom.id;
  const p=proposeNextBlock(s);expect(p.changes.find(c=>c.id===e.id).to).toBe(custom.id);
  const n=applyNextBlock(s,p,{[e.id]:'recommendation'}).state,restored=(await parseBackupArchive((await buildBackupArchive(n,[])).bytes)).state;
  const replacement=restored.program.days[0].exercises.find(item=>item.id===e.id);expect(replacement.exerciseId).toBe(custom.id);expect(replacement.importedName).toBe(custom.name);expect(restored.planVersions.at(-1).source).toBe('Next block');
 });
 it('a throwing persistence adapter leaves the original state untouched',()=>{const s=completedBlockFixture(),before=JSON.stringify(s);const r=applyNextBlock(s,proposeNextBlock(s),{},{persist:()=>{throw new Error('QuotaExceededError');}});expect(r.status).toBe('persistence-failed');expect(r.state).toBe(s);expect(JSON.stringify(s)).toBe(before);});
 it('backup rejects a malformed archived review',async()=>{const seed=completedBlockFixture();const n=applyNextBlock(seed,proposeNextBlock(seed)).state;n.completedTrainingBlocks[0].reviewSummary.rows={};await expect(buildBackupArchive(n,[])).rejects.toThrow();});
 function replacementFixture(){const s=completedBlockFixture(),day=s.program.days[0],e=day.exercises[0],candidate=nextBlockReplacementChoices(s,e)[0];expect(candidate).toBeTruthy();for(const w of s.workouts.filter(w=>w.programDayId===day.id&&!w.trainingBlock.plannedDeload).slice(0,4))w.exercises.find(item=>item.id===e.id).exerciseId=candidate.id;return {s,e,candidate};}
 it('offers a factual frequent substitution for explicit review',()=>{const {s,e,candidate}=replacementFixture(),p=proposeNextBlock(s);expect(p.changes.find(c=>c.id===e.id)).toMatchObject({kind:'replacement',to:candidate.id});});
 it('rejecting replacement keeps the original exercise and history',()=>{const {s,e}=replacementFixture(),n=applyNextBlock(s,proposeNextBlock(s),{[e.id]:'keep'}).state;expect(n.program.days[0].exercises[0].exerciseId).toBe(e.exerciseId);expect(n.workouts).toEqual(s.workouts);});
 it('accepting replacement clears old loads and uses replacement identity',()=>{const {s,e,candidate}=replacementFixture(),n=applyNextBlock(s,proposeNextBlock(s),{[e.id]:'recommendation'}).state;expect(n.program.days[0].exercises[0].exerciseId).toBe(candidate.id);expect(n.program.days[0].exercises[0].sets.every(set=>set.weight===null)).toBe(true);});
 it('invalid replacement selection cannot mutate anything',()=>{const {s,e}=replacementFixture(),r=applyNextBlock(s,proposeNextBlock(s),{[e.id]:'not-a-compatible-id'});expect(r.status).toBe('invalid');expect(r.state).toBe(s);});
 it('one-off equipment adaptations never become permanent replacement evidence',()=>{const {s,e}=replacementFixture();for(const w of s.workouts)w.adjustment={mode:'different-equipment'};expect(proposeNextBlock(s).changes.some(c=>c.id===e.id&&c.kind==='replacement')).toBe(false);});
 it('unknown custom metadata defaults to keep',()=>{const s=completedBlockFixture(),e=s.program.days[0].exercises[0];e.exerciseId='unknown-custom';e.importedName='Unspecified gym machine';e.importedExercise={id:e.exerciseId,name:e.importedName};expect(proposeNextBlock(s).changes.some(c=>c.id===e.id)).toBe(false);});
 it('year boundary produces a real future Week 1 date',()=>{const s=completedBlockFixture(),p=proposeNextBlock(s,{now:Date.parse('2026-12-31T12:00:00Z')});expect(p.startDate).toBe('2027-01-01');});
 it('regenerates deterministically without saving proposal',()=>{const s=completedBlockFixture();expect(proposeNextBlock(s,{now:Date.parse('2026-09-06T12:00:00Z')})).toEqual(proposeNextBlock(s,{now:Date.parse('2026-09-06T12:00:00Z')}));});
 it('applies one new identity and one plan version with immutable old history',()=>{const s=completedBlockFixture(),before=JSON.stringify(s.workouts),p=proposeNextBlock(s),n=applyNextBlock(s,p).state;expect(n.program.trainingBlock.currentWeek).toBe(1);expect(n.program.trainingBlock.completed).toBe(false);expect(n.program.trainingBlock.id).not.toBe(s.program.trainingBlock.id);expect(n.planVersions.length).toBe(s.planVersions.length+1);expect(n.planVersions.at(-1).source).toBe('Next block');expect(JSON.stringify(n.workouts)).toBe(before);expect(n.completedTrainingBlocks[0].reviewSummary.completedSessions).toBe(18);expect(applyNextBlock(n,p).status).toBe('stale');});
 it('repeat retains week definitions without copying history',()=>{const s=completedBlockFixture(),p=proposeNextBlock(s,{repeat:true}),n=applyNextBlock(s,p).state;expect(p.changes).toEqual([]);expect(n.program.days).toEqual(s.program.days);expect(n.workouts).toEqual(s.workouts);expect(n.program.trainingBlock.weeks.map(w=>w.repOffset)).toEqual(s.program.trainingBlock.weeks.map(w=>w.repOffset));});
 it('persistence failure leaves old state and version count intact',()=>{const s=completedBlockFixture(),before=JSON.stringify(s),persist=vi.fn(()=>false),r=applyNextBlock(s,proposeNextBlock(s),{},{persist});expect(r.status).toBe('persistence-failed');expect(r.state).toBe(s);expect(JSON.stringify(s)).toBe(before);expect(persist).toHaveBeenCalledTimes(1);});
 for(const [label,mutate] of [['plan edit',s=>s.program.days[0].exercises[0].repMax++],['block edit',s=>s.program.trainingBlock.currentWeek--],['workout correction',s=>s.workouts[0].exercises[0].sets[0].reps++],['flexible resolution',s=>s.flexibleWeek={revision:1}],['plan restore',s=>s.planVersions.push({id:'restored'})],['gym switch',s=>s.defaultGymProfileId='other'],['active workout',s=>s.activeWorkout={id:'active'}]])it(`rejects stale ${label}`,()=>{const s=completedBlockFixture(),p=proposeNextBlock(s);mutate(s);expect(applyNextBlock(s,p).status).toBe('stale');});
 it('blocks an already active workout even when proposal was built during it',()=>{const s=completedBlockFixture();s.activeWorkout={id:'active'};expect(applyNextBlock(s,proposeNextBlock(s)).status).toBe('active');});
 it('approved load survives backup/reload and is not overwritten by old history at the first exposure',async()=>{const s=completedBlockFixture(),p=proposeNextBlock(s),c=p.changes.find(c=>c.kind==='load'),applied=applyNextBlock(s,p,{[c.id]:'recommendation'}).state,n=(await parseBackupArchive((await buildBackupArchive(applied,[])).bytes)).state;n.selectedDate=n.program.trainingBlock.startDate;const day=n.program.days.find(d=>d.id===c.dayId),w=startWorkout(n,prescribeTrainingBlockWorkout(n,day)),e=w.exercises.find(e=>e.id===c.id);expect(e.sets[0].weight).toBe(c.to);expect(e.sets[0].weightProvenance).toBe('next-block-review');});
 it('keeping a proposed load does not overwrite the existing plan',()=>{const s=completedBlockFixture(),p=proposeNextBlock(s),n=applyNextBlock(s,p).state;expect(n.program.days).toEqual(s.program.days);});
 it('clears unstarted temporary state only on accepted transition',()=>{const s=completedBlockFixture();s.todayAdaptation={id:'temporary'};s.flexibleWeek={schemaVersion:1,sessions:{},revision:1};const n=applyNextBlock(s,proposeNextBlock(s)).state;expect(n.todayAdaptation).toBe(null);expect(n.flexibleWeek).toBe(null);expect(s.todayAdaptation).toBeTruthy();});
 it('Coach accurately reports completed versus new current block',()=>{const s=completedBlockFixture();expect(coachContext(s).blockReview.status).toBe('completed-review-available');const n=applyNextBlock(s,proposeNextBlock(s)).state;expect(coachContext(n).blockReview).toMatchObject({status:'in-progress',currentWeek:1,nextBlockApplied:true});});
 for(const applied of [false,true])it(`backup restores ${applied?'new':'completed'} block and review evidence`,async()=>{let s=completedBlockFixture();if(applied)s=applyNextBlock(s,proposeNextBlock(s)).state;const archive=await buildBackupArchive(s,[]);const parsed=await parseBackupArchive(archive.bytes);expect(parsed.state.program.trainingBlock).toEqual(s.program.trainingBlock);expect(parsed.state.completedTrainingBlocks).toEqual(s.completedTrainingBlocks);expect(parsed.state.planVersions).toEqual(s.planVersions);});
});
