import React,{act,createRef} from 'react';
import {createRoot} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {ExerciseNavigationButton} from './ExerciseNavigationButton.jsx';
let host,root,button,click;
beforeEach(()=>{globalThis.IS_REACT_ACT_ENVIRONMENT=true;host=document.createElement('div');document.body.append(host);root=createRoot(host);click=vi.fn();});
afterEach(()=>{act(()=>root.unmount());host.remove();vi.restoreAllMocks();});
function mount(props={}){act(()=>root.render(<ExerciseNavigationButton onClick={click} {...props}>Romanian Deadlift</ExerciseNavigationButton>));button=host.querySelector('button');vi.spyOn(button,'getBoundingClientRect').mockReturnValue({left:0,top:0,right:300,bottom:60,width:300,height:60});}
function pointer(type,values={}){const event=new Event(type,{bubbles:true,cancelable:true});Object.assign(event,{pointerId:1,pointerType:'touch',isPrimary:true,button:0,clientX:100,clientY:30,...values});act(()=>button.dispatchEvent(event));return event;}
const pressed=()=>button.hasAttribute('data-row-pressed');
it('gives immediate feedback, clears on release and leaves one native click untouched',()=>{mount();expect(pointer('pointerdown').defaultPrevented).toBe(false);expect(pressed()).toBe(true);expect(button.getAttribute('aria-pressed')).toBeNull();expect(click).not.toHaveBeenCalled();pointer('pointerup');expect(pressed()).toBe(false);act(()=>button.click());expect(click).toHaveBeenCalledOnce();});
it.each(['pointercancel','pointerout','lostpointercapture'])('clears cancelled feedback for %s',type=>{mount();pointer('pointerdown');pointer(type,{relatedTarget:document.body});expect(pressed()).toBe(false);expect(click).not.toHaveBeenCalled();});
it('cancels vertical movement without preventing scrolling and does not relight on re-entry',()=>{mount();pointer('pointerdown');expect(pointer('pointermove',{clientY:45}).defaultPrevented).toBe(false);expect(pressed()).toBe(false);pointer('pointermove');expect(pressed()).toBe(false);});
it('cancels when the finger leaves bounds, even within the movement tolerance',()=>{mount();pointer('pointerdown',{clientX:298});pointer('pointermove',{clientX:302});expect(pressed()).toBe(false);});
it.each(['scroll','visibilitychange','blur'])('clears held feedback on %s',type=>{mount();pointer('pointerdown');act(()=>(type==='blur'?window:document).dispatchEvent(new Event(type)));expect(pressed()).toBe(false);});
it('keeps touch hover suppressed after cancellation and restores real mouse hover eligibility',()=>{mount();pointer('pointerdown');pointer('pointercancel');expect(button.hasAttribute('data-row-touch')).toBe(true);pointer('pointermove',{pointerType:'mouse'});expect(button.hasAttribute('data-row-touch')).toBe(false);});
it.each([' ','Enter'])('retains native keyboard activation and independent focus for %s',key=>{mount();act(()=>button.focus());const event=new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true});act(()=>button.dispatchEvent(event));expect(event.defaultPrevented).toBe(false);expect(pressed()).toBe(true);act(()=>button.dispatchEvent(new KeyboardEvent('keyup',{key,bubbles:true})));expect(pressed()).toBe(false);expect(document.activeElement).toBe(button);});
it('composes existing pointer/keyboard handlers and forwards the actual DOM ref',()=>{const ref=createRef(),down=vi.fn(),key=vi.fn();mount({ref,onPointerDown:down,onKeyDown:key});expect(ref.current).toBe(button);pointer('pointerdown');act(()=>button.dispatchEvent(new KeyboardEvent('keydown',{key:'F10',shiftKey:true,bubbles:true})));expect(down).toHaveBeenCalledOnce();expect(key).toHaveBeenCalledOnce();});
it('ignores secondary pointers and right clicks; disabling removes an in-flight press',()=>{mount();pointer('pointerdown',{button:2});expect(pressed()).toBe(false);pointer('pointerdown',{isPrimary:false});expect(pressed()).toBe(false);pointer('pointerdown');act(()=>root.render(<ExerciseNavigationButton disabled>Romanian Deadlift</ExerciseNavigationButton>));expect(pressed()).toBe(false);});
it('unmount releases temporary scroll listeners and a held visual state',()=>{mount();const remove=vi.spyOn(document,'removeEventListener');pointer('pointerdown');act(()=>root.render(null));expect(button.hasAttribute('data-row-pressed')).toBe(false);expect(remove.mock.calls.some(([event,,capture])=>event==='scroll'&&capture===true)).toBe(true);});
