import React,{act,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {FlexibleWeekSheet} from './FlexibleWeekSheet.jsx';
import {MissedWorkoutFeedbackProvider} from './MissedWorkoutFeedback.jsx';
import {TemporaryScheduleSummary} from './TemporaryScheduleSummary.jsx';
import {adjustWeekState} from './fixtures/adjustWeekState.js';
import {flexibleSessions,proposeFlexibleWeek,applyFlexibleWeek,temporaryScheduleReview} from './flexibleWeek.js';
import {deserializeState,STORAGE_KEY} from './domain.js';
let root,current,change;
beforeEach(()=>{globalThis.IS_REACT_ACT_ENVIRONMENT=true;vi.useFakeTimers();vi.setSystemTime(new Date('2026-09-28T12:00:00'));localStorage.clear();const node=document.createElement('div');document.body.append(node);root=createRoot(node);});
afterEach(()=>{act(()=>root.unmount());document.body.innerHTML='';vi.restoreAllMocks();vi.useRealTimers();});
const button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent===text);
const click=text=>act(()=>button(text).click());
const base=()=>adjustWeekState({shifted:false,history:1});
const id=(s,date)=>flexibleSessions(s).find(i=>i.originalDate===date).logicalSessionId;
const skipped=s=>applyFlexibleWeek(s,proposeFlexibleWeek(s,{mode:'skip',sessionId:id(s,'2026-09-29')})).state;
const Header=({title,onBack,onClose})=><header><h2>{title}</h2>{onBack&&<button className="detail-header-back" onClick={onBack}>Back</button>}<button onClick={onClose}>Close</button></header>;
function draw(initial=base(),request={}){function Harness(){const[state,setState]=useState(initial),[detail,setDetail]=useState(request);current=state;change=fn=>act(()=>setState(fn));return <MissedWorkoutFeedbackProvider state={state} update={setState} onViewSchedule={()=>setDetail({reviewExisting:true})}><TemporaryScheduleSummary state={state} update={setState} review={temporaryScheduleReview(state)} onView={()=>setDetail({reviewExisting:true})}/>{detail&&<FlexibleWeekSheet state={state} update={setState} close={()=>setDetail(null)} Header={Header} request={detail}/>}</MissedWorkoutFeedbackProvider>;}act(()=>root.render(<Harness/>));}
function applySkip(){click('Move a workoutChoose one session and another date.');const row=[...document.querySelectorAll('[data-session-id]')].find(n=>n.textContent.includes('NOGE A')&&n.textContent.includes('Sep 29'));act(()=>row.click());click('Skip this session');click('USE THIS SCHEDULE');}
const notice=()=>document.querySelector('.rook-snackbar');
it('Apply shows one surviving canonical Schedule updated / Undo notice and closes the sheet',()=>{
 draw();applySkip();expect(document.querySelector('.flexible-week-sheet')).toBeNull();expect(notice().textContent).toBe('Schedule updatedUndo');expect(document.querySelectorAll('.rook-snackbar')).toHaveLength(1);expect(button('View schedule')).toBeDefined();
 const undo=notice().querySelector('button');act(()=>{undo.click();undo.click();});expect(current.flexibleWeek.sessions).toEqual({});expect(notice()).toBeNull();expect(current.flexibleWeek.revision).toBe(2);
});
it('timeout dismissal keeps the applied revision, which survives reload',()=>{draw();applySkip();const applied=structuredClone(current.flexibleWeek);act(()=>vi.advanceTimersByTime(5001));expect(notice()).toBeNull();expect(current.flexibleWeek).toEqual(applied);expect(deserializeState(localStorage.getItem(STORAGE_KEY)).flexibleWeek).toEqual(applied);});
it('swipe dismissal keeps the applied revision and shared pointer interaction pauses timeout',()=>{
 draw();applySkip();const applied=structuredClone(current.flexibleWeek);
 const pointer=(node,type,x)=>{const e=new Event(type,{bubbles:true,cancelable:true});for(const[k,v]of Object.entries({pointerId:1,isPrimary:true,clientX:x,clientY:20}))Object.defineProperty(e,k,{value:v});act(()=>node.dispatchEvent(e));};
 act(()=>vi.advanceTimersByTime(4500));pointer(notice(),'pointerdown',10);act(()=>vi.advanceTimersByTime(5000));expect(notice()).not.toBeNull();pointer(window,'pointermove',180);pointer(window,'pointerup',180);act(()=>vi.advanceTimersByTime(180));expect(notice()).toBeNull();expect(current.flexibleWeek).toEqual(applied);
});
it('stale Undo never overwrites newer state and offers View schedule',()=>{draw();applySkip();change(s=>({...s,flexibleWeek:{...s.flexibleWeek,generation:'other-device',revision:s.flexibleWeek.revision+1}}));const before=current;click('Undo');expect(current).toBe(before);expect(notice()).toBeNull();expect(document.querySelector('[role="alert"]').textContent).toContain('changed');act(()=>document.querySelector('[role="alert"] button').click());expect(document.querySelector('header h2').textContent).toBe('Temporary schedule');});
it('View schedule has canonical title, changed-only list and Edit / Restore actions',()=>{draw(skipped(base()),{reviewExisting:true});expect(document.querySelector('header h2').textContent).toBe('Temporary schedule');expect(document.querySelector('h1').textContent).toBe('Temporary schedule');expect(document.body.textContent).toContain('1 change');expect(document.querySelectorAll('.flexible-week-review article')).toHaveLength(1);expect(document.querySelector('article').textContent).toContain('SKIPPED');expect(button('EDIT SCHEDULE')).toBeDefined();expect(button('Restore original schedule')).toBeDefined();click('EDIT SCHEDULE');expect(document.querySelector('h1').textContent).toBe('What changed?');expect(button('View current schedule1 change')).toBeDefined();expect(document.body.textContent).not.toContain('0 moved');});
it('cancel Restore changes no domain state; confirm restores safe overrides without touching history',()=>{
 draw(skipped(base()),{reviewExisting:true});const before=structuredClone(current);click('Restore original schedule');expect(document.querySelector('h1').textContent).toBe('Restore original schedule?');click('KEEP TEMPORARY SCHEDULE');expect(current).toEqual(before);expect(document.querySelector('header h2').textContent).toBe('Temporary schedule');
 click('Restore original schedule');click('RESTORE ORIGINAL SCHEDULE');expect(current.flexibleWeek.sessions).toEqual({});expect(current.workouts).toEqual(before.workouts);expect(current.program).toEqual(before.program);expect(notice().textContent).toBe('Schedule updatedUndo');
});
it('Restore review cannot clobber a newer schedule revision',()=>{draw(skipped(base()),{reviewExisting:true});click('Restore original schedule');change(s=>({...s,flexibleWeek:{...s.flexibleWeek,generation:'newer'}}));const before=current;click('RESTORE ORIGINAL SCHEDULE');expect(current).toBe(before);expect(document.querySelector('[role="alert"]').textContent).toContain('changed');});
it('failed Apply writes leave the previous schedule and allow a retry',()=>{draw();click('Move a workoutChoose one session and another date.');const row=[...document.querySelectorAll('[data-session-id]')].find(n=>n.textContent.includes('NOGE A')&&n.textContent.includes('Sep 29'));act(()=>row.click());click('Skip this session');const before=current,fail=vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('full');});click('USE THIS SCHEDULE');expect(current).toBe(before);expect(notice()).toBeNull();expect(document.querySelector('[role="alert"]').textContent).toContain('unchanged');fail.mockRestore();click('TRY AGAIN');expect(notice()).not.toBeNull();});
it('What changed hides both non-actionable missed and availability choices while retaining useful Move',()=>{
 vi.setSystemTime(new Date('2026-10-04T12:00:00'));const s=base();s.workouts.push(...flexibleSessions(s).filter(i=>i.scheduledDate<'2026-10-04').map(i=>({id:'done-'+i.logicalSessionId,logicalSessionId:i.logicalSessionId,completedAt:'2026-10-02T12:00:00'})));
 draw(s);expect(document.body.textContent).not.toContain('I missed a workout');expect(document.body.textContent).not.toContain('My available days changed');expect(document.body.textContent).not.toContain('No missed workouts');expect(button('Move a workoutChoose one session and another date.')).toBeDefined();
});
it('future source does not advertise an empty Adjust remaining week action',()=>{vi.setSystemTime(new Date('2026-10-04T12:00:00'));const s=base();s.workouts.push(...flexibleSessions(s).filter(i=>i.scheduledDate<'2026-10-04').map(i=>({id:'done-'+i.logicalSessionId,logicalSessionId:i.logicalSessionId,completedAt:Date.now()})));draw(s,{sessionId:id(s,'2026-10-06'),destination:true});expect(button('Adjust remaining week')).toBeUndefined();expect(button('Skip this session')).toBeDefined();});
it('availability losing all sources while open offers a real Move flow instead of an empty date picker',()=>{
 draw();click('My available days changedRearrange workouts through this Sunday.');change(s=>({...s,workouts:[...s.workouts,...flexibleSessions(s).filter(i=>i.originalDate<='2026-10-04').map(i=>({id:'remote-done-'+i.logicalSessionId,logicalSessionId:i.logicalSessionId,completedAt:Date.now()}))]}));
 expect(document.querySelector('h1').textContent).toBe('Your remaining week is already set');expect(document.querySelectorAll('[data-available-date]')).toHaveLength(0);click('MOVE A WORKOUT');expect(document.querySelector('h1').textContent).toBe('Choose a workout');expect(document.querySelectorAll('.flexible-workout-list button').length).toBeGreaterThan(0);
});
it('skip Review uses truthful scope and retains back-to-back warnings',()=>{draw();click('Move a workoutChoose one session and another date.');const row=[...document.querySelectorAll('[data-session-id]')].find(n=>n.textContent.includes('NOGE A')&&n.textContent.includes('Sep 29'));act(()=>row.click());click('Skip this session');expect(document.body.textContent).not.toContain('Dates only');expect(document.body.textContent).toContain('Temporary changes only');expect(document.body.textContent).toContain('This creates back-to-back training days.');expect(button('USE THIS SCHEDULE')).toBeDefined();});
