// New coverage corpus. The previously accepted 30-case corpus is not rebuilt.
export const hybridImportCorpus = [
  {id:'precise',source:'Monday: Upper\nBench Press 3x8 60kg',blocks:1,counts:[3],reps:[[8,8]],loads:[60]},
  {id:'ranges',source:'Monday: Lower\nSquat 4x6–8 132.5kg',blocks:1,counts:[4],reps:[[6,8]],loads:[132.5]},
  {id:'slovenian-partial',source:'Ponedeljek: Prsa\nChest flys - 4 seti',blocks:1,counts:[4],reps:[[null,null]]},
  {id:'mixed-minimum',source:'Monday: Push\nBench press - 3 seti vsaj 3 repi',blocks:1,counts:[3],reps:[[3,null]]},
  {id:'mixed-maximum',source:'Monday: Push\nBench press - 3 seti največ 8 repi',blocks:1,counts:[3],reps:[[null,8]]},
  {id:'english-long-tail',source:'Monday: Upper\nPlease perform Cable Row for three sets of ten reps.',blocks:1,counts:[3],reps:[[10,10]],aiName:'Cable Row'},
  {id:'slovenian-long-tail',source:'Ponedeljek: Hrbet\nNaredi Cable Row, tri sete po deset repov.',blocks:1,counts:[3],reps:[[10,10]],aiName:'Cable Row'},
  {id:'bullets',source:'Monday: Upper\n- Bench Press 3x8\n- Cable Row 3x10',blocks:2,counts:[3,3],reps:[[8,8],[10,10]]},
  {id:'table',source:'Day\tExercise\tSets\tReps\tLoad\nMonday\tBench Press\t3\t8\t60 kg\nThursday\tSquat\t4\t6–8\t132.5 kg',blocks:2,counts:[3,4],days:['Mon','Thu']},
  {id:'body-part-sections',source:'Day 1: Upper\nChest\nBench Press - 3 seti\nBack\nCable Row - 4 seti',blocks:2,counts:[3,4],reps:[[null,null],[null,null]]},
  {id:'optional',source:'Monday: Push\n(Optional)\nPlate front raises - 3 seti',blocks:1,counts:[3],optional:1},
  {id:'choice',source:'Monday: Push\nShoulder press (any variation) - 3-4 sets',blocks:1,counts:[0],choice:1},
  {id:'roles',source:'Monday: Upper\nBench Press - 2 warm-up sets + 1 top set + 2 back-off sets',blocks:2,counts:[1,2],roles:['Top set','Back-off sets'],warmup:2},
  {id:'drop',source:'Monday: Push\nLateral raises - 3 seti\n+ 1 dropset',blocks:2,counts:[3,1],methods:['standard','drop']},
  {id:'rest-pause',source:'Monday: Push\nBench Press - 3 seti rest pause 8–10 reps',blocks:1,counts:[3],reps:[[8,10]],methods:['rest_pause']},
  {id:'failure',source:'Monday: Push\nDips - 3 seti do failure',blocks:1,counts:[3],reps:[[null,null]],failure:true},
  {id:'amrap',source:'Monday: Pull\nPull Up 3xAMRAP optional added load',blocks:1,counts:[3],reps:[[null,null]]},
  {id:'timed-range',source:'Monday: Core\nPlank - 3 seti 30–45 sec',blocks:1,counts:[3],reps:[[30,45]],measure:'seconds'},
  {id:'rest-not-duration',source:'Monday: Upper\nBench Press - 3 seti 8 reps rest 90 sec',blocks:1,counts:[3],reps:[[8,8]],rest:90},
  {id:'per-side',source:'Monday: Lower\nSplit Squat - 3 seti 8–10 reps / stran',blocks:1,counts:[3],reps:[[8,10]],mode:'per_side'},
  {id:'location-rir',source:'Monday: Home\nPush Up - 3 seti 12 reps bodyweight RIR 0\nFriday: Gym\nBench Press 3x8 60kg',blocks:2,counts:[3,3],locations:['Home','Commercial gym'],rir:[0,null]},
  {id:'circuit-blocked',source:'Monday: Circuit\n3 rounds\nPush Up 10 reps\nSquat 15 reps',circuit:true},
  {id:'superset',source:'Monday: Upper\nSuperset: Cable Fly 3x12 + Cable Row 3x12',blocks:2,counts:[3,3],superset:true},
  {id:'unknown-exercise',source:'Monday: Upper\nZorbic Lever - 3 seti',blocks:1,counts:[3],reps:[[null,null]]},
  {id:'distance-needs-review',source:'Monday: Carry\nFarmer Carry - 3 seti 20 m',blocks:1,counts:[3],sourceEdit:true},
  {id:'negative-load-needs-review',source:'Monday: Pull\nPull Up - 3 seti 8 reps -20kg assistance',blocks:1,counts:[3],loads:[null],sourceEdit:true},
  {id:'malformed-partial',source:'Monday: Upper\nBench Press ??? kg; sets unknown',blocks:1,counts:[0],reps:[[null,null]]},
  {id:'non-workout',source:'Train harder someday; not a workout plan.',rejected:true},
  {id:'mixed-superset-partial',source:'Monday: Upper\nSuperset: Cable Fly 3x12 + Cable Row 3x12\nPlate front raises - 3 seti',blocks:3,counts:[3,3,3],superset:true},
  {id:'mixed-inline-partial',source:'Monday: Bench Press 3x8; Cable Row 3x10. Thursday: Squat 4x6; Leg Curl 3x12.\nFriday: Upper\nChest Fly - 4 seti',blocks:5,counts:[3,3,4,3,4],days:['Mon','Thu','Fri']},
  {id:'mixed-table-partial',source:'Day\tExercise\tSets\tReps\tLoad\nMonday\tBench Press\t3\t8\t60 kg\nThursday\tSquat\t4\t6–8\t132.5 kg\nFriday: Upper\nChest Fly - 4 seti',blocks:3,counts:[3,4,4],days:['Mon','Thu','Fri'],loads:[60,132.5,null]},
];
