export const importAdversarialFixtures = [
  ['tight Unicode','Tue:\nSeated Cable Row 4×9',1,1],
  ['Slovenian spacing','pon : roke\n  dumbbell curl   2 X 11  ',1,1],
  ['bodyweight','Thursday\nPush-up 2x12 BW',1,1],
  ['same-line entries','Wednesday\nBench Press 3x8 80kg; Cable Fly 2x12',1,2],
  ['decimal different position','Friday\nDumbbell Curl - 12,5 kg - 3x9',1,1],
  ['band resistance','Saturday\nBand Pull Apart 3x20 medium band',1,1],
  ['machine pin','Monday\nCable Row 3x8 machine pin 8',1,1],
  ['tempo','Tuesday\nRomanian Deadlift 3x8\nSlow eccentric, pause below knee.',1,1],
  ['alias spelling','Wednesday\nAtlantis high row 2x9',1,1],
  ['misspelling','Friday\nDumbell Hammer Curl 3x11',1,1],
  ['ambiguous effort','Thursday\nOverhead Press 4x5 @3',1,1],
  ['RPE reversed','Saturday\nHack Squat 3x7 8 RPE',1,1],
  ['unlabelled possible load','Monday\nBench Press 3x9 75',1,1],
  ['repeated entries','Tuesday\nCable Fly 2x10\nCable Fly 1x15',1,2],
  ['two workouts same date','Wednesday - AM\nCable Row 2x10\nWednesday - PM\nLeg Press 2x10',2,2],
  ['unknown calendar','Workout B\nRomanian Deadlift 3x7',1,1],
  ['left right instruction','Thursday\nDumbbell Curl 2x10 L/R',1,1],
  ['drop note','Friday\nLateral Raise 3x14 + drop set',1,1],
  ['rest pause note','Saturday\nCable Curl 2x10 rest-pause',1,1],
  ['third-set amrap','Sunday\nLat Pulldown 2x9\nSet 3 AMRAP',1,1],
  ['equal superset','Monday\nC1 Cable Curl 2x9\nC2 Cable Pushdown 2x12',1,2],
  ['incomplete superset','Tuesday\nA1 Cable Fly 2x10',1,1],
  ['alternatives','Wednesday\nBench Press 3x8 / Machine Chest Press 3x10',1,1],
  ['recovery after work','Friday\nLeg Press 3x10\nSaturday - Recovery\nBalance 2x20 s',1,1],
  ['warmup movements','Sunday\nWarm-up\nWalking 5 min\nWorkout\nGoblet Squat 3x10',1,1],
  ['rest line','Monday\nBench Press 3x7\nRest: 120 sec',1,1],
  ['mixed language','PET - zgornji del\nIncline Dumbbell Press 3x9\nCable Row 2x11\nLahko dodaš težo, če je tehnika dobra.',1,2],
  ['explicit week changes','Week 4\nBench Press 3x9\nWeek 5\nBench Press 4x8',0,0],
  ['no prescription','Train harder someday; not a workout plan.',0,0],
  ['malformed load-only','Bench Press ??? kg; sets unknown',0,0],
].map(([name,text,days,exercises])=>({name,text,days,exercises}));
