import {it,expect} from 'vitest';
import {AIService,parseStructuredTrainingNotes} from './aiService.js';
import {blankState} from './domain.js';
const parse=source=>AIService.importTrainingPlan(blankState().profile,source,{review:true});
it.each(['; ','. '])('splits exercise boundary %s within explicit days',async separator=>{
 const source=`Monday: Bench Press 3x8 60 kg${separator}Cable Row 3x10. Thursday: Squat 4x6${separator}Leg Curl 3x12.`;
 const r=await parse(source);expect(r.program.days.map(d=>d.weekday)).toEqual(['Mon','Thu']);expect(r.program.days.map(d=>d.exercises.length)).toEqual([2,2]);expect(r.sourceReview.issues).toEqual([]);
 expect(r.program.days.map(d=>d.name)).toEqual(['Workout','Workout']);expect(r.program.days[0].exercises[0].sets[0].weight).toBe(60);
 const raw=parseStructuredTrainingNotes(source,blankState().profile,{review:true});for(const exercise of raw.days.flatMap(d=>d.exercises)){expect(source.slice(exercise.sourceSpan.start,exercise.sourceSpan.end)).toBe(exercise.sourceSpan.text);expect(exercise.sourceSpan.text).not.toMatch(/Monday|Thursday/);}
});
it('handles a single day',async()=>{const r=await parse('Monday: Bench Press 3x8; Cable Row 3x10.');expect(r.program.days).toHaveLength(1);expect(r.program.days[0].exercises).toHaveLength(2);expect(r.sourceReview.issues).toEqual([]);});
it.each([['Mon','Thu'],['Ponedeljek','Četrtek'],['Pon','Čet'],['  mOn  ',' THu ']])('handles %s and %s on separate lines',async(a,b)=>{const r=await parse(`${a}: Pull Up 3xAMRAP; Row 3x8.\n${b}: Squat 4x6–8; Leg Curl 3x12.`);expect(r.program.days.map(d=>d.weekday)).toEqual(['Mon','Thu']);expect(r.program.days.map(d=>d.exercises.length)).toEqual([2,2]);expect(r.program.days[0].exercises[0].sets.map(s=>s.reps)).toEqual([null,null,null]);expect(r.program.days[1].exercises[0].repMax).toBe(8);expect(r.sourceReview.issues.filter(i=>i.field==='alternative'||i.field==='day')).toEqual([]);});
it('retains one genuine alternative without including the next exercise',async()=>{const r=await parse('Monday: Leg Press 3x9 155kg / Leg press machine 3x8 173kg; Leg Curl 3x12.');const issues=r.sourceReview.issues.filter(i=>i.field==='alternative');expect(issues).toHaveLength(1);expect(issues[0].source).not.toContain('Leg Curl');expect(issues[0].options).toHaveLength(2);expect(r.program.days[0].exercises).toHaveLength(2);});
it('preserves hyphenated names, decimal loads and instruction sentences',async()=>{const source='Monday: Single-Leg Leg Press 3x8 132.5kg. Pause at bottom. Cable Row 3x10.';const r=await parse(source);expect(r.program.days[0].exercises).toHaveLength(2);expect(r.program.days[0].exercises[0].sets[0].weight).toBe(132.5);const raw=parseStructuredTrainingNotes(source,blankState().profile,{review:true});expect(raw.days[0].exercises[0].sourceSpan.text).toContain('Pause at bottom');expect(JSON.stringify(r.program.importMetadata)).toContain('Pause at bottom');});
it('leaves generic Workout A scheduling unresolved',async()=>{const r=await parse('Workout A: Bench Press 3x8; Cable Row 3x10.');expect(r.program.days[0].weekday).toBeNull();expect(r.program.days[0].exercises).toHaveLength(2);expect(r.sourceReview.issues.filter(i=>i.field==='day')).toHaveLength(1);});
it('retains explicitly named multiline headings',async()=>{const r=await parse('Monday: Upper\nBench Press 3x8\nCable Row 3x10');expect(r.program.days[0].name).toBe('Upper');});
