import React,{act,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {blankState,buildProgram,deserializeState,serializeState,STORAGE_KEY} from './domain.js';
import {missedFlexibleSessions,proposeFlexibleWeek,applyFlexibleWeek} from './flexibleWeek.js';
import {MissedWorkoutSummary} from './missedWorkoutPresentation.jsx';
import {dismissMissedReminder,missedReminderKey} from './missedWorkoutActions.js';
let root,current;
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-09-18T12:00:00'));localStorage.clear();});
afterEach(()=>{act(()=>root?.unmount());root=null;document.body.innerHTML='';vi.restoreAllMocks();vi.useRealTimers();});
function fixture(single=false){let s=blankState();Object.assign(s.profile,{goal:'Build muscle',experience:'Intermediate',daysPerWeek:3,availableDays:['Mon','Wed','Fri'],sessionMinutes:60,equipment:['full gym'],environment:'Commercial gym',priorities:['Balanced'],onboardingComplete:true});s.program=buildProgram(s.profile);s.program.trainingBlock.startDate='2026-09-14';s=deserializeState(s);if(single){const b=missedFlexibleSessions(s)[1];s=applyFlexibleWeek(s,proposeFlexibleWeek(s,{mode:'skip',sessionId:b.logicalSessionId})).state;}return s;}
function render(initial,onSelect=()=>{}){const host=document.createElement('main');document.body.append(host);root=createRoot(host);function Harness(){const [state,setState]=useState(initial);current=state;return <MissedWorkoutSummary state={state} onSelect={onSelect} update={fn=>setState(fn)}/>;}act(()=>root.render(<Harness/>));}
const dismiss=()=>document.querySelector('[aria-label="Dismiss missed-workout reminder"]');
it.each([false,true])('dismiss persists without skipping any occurrence, single=%s',single=>{const s=fixture(single),before=structuredClone(s),ids=missedFlexibleSessions(s).map(x=>x.logicalSessionId);render(s);const button=dismiss(),write=vi.spyOn(Storage.prototype,'setItem');act(()=>{button.click();button.click();});expect(write.mock.calls.filter(c=>c[0]===STORAGE_KEY)).toHaveLength(1);expect(dismiss()).toBeNull();expect(current).toEqual({...before,dismissedMissedReminderKey:missedReminderKey(before)});expect(s).toEqual(before);const restored=deserializeState(localStorage.getItem(STORAGE_KEY));expect(missedFlexibleSessions(restored).map(x=>x.logicalSessionId)).toEqual(ids);act(()=>root.unmount());root=null;render(restored);expect(dismiss()).toBeNull();});
it('failed persistence leaves reminder and schedule intact and permits retry',()=>{const s=fixture();render(s);const fail=vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('full');});act(()=>dismiss().click());expect(current).toEqual(s);expect(dismiss()).not.toBeNull();expect(document.querySelector('[role="alert"]').textContent).toContain('still visible');fail.mockRestore();act(()=>dismiss().click());expect(dismiss()).toBeNull();});
it.each([false,true])('routes the native reminder by occurrence ID or count, single=%s',single=>{const state=fixture(single),select=vi.fn(),before=serializeState(state);render(state,select);const missed=missedFlexibleSessions(state),target=document.querySelector('.today-missed-open');expect(target.tagName).toBe('BUTTON');expect(document.body.textContent).not.toMatch(/View all|Oldest:/);if(single){expect(document.body.textContent).toContain('MISSED WORKOUT');expect(document.body.textContent).toContain('Mon, Sep 14');expect(target.getAttribute('aria-label')).toContain(missed[0].workout.name);}else expect(target.textContent).toContain('2 missed workouts');act(()=>target.click());expect(select).toHaveBeenCalledWith(single?{sessionId:missed[0].logicalSessionId}:{missed:true});expect(serializeState(state)).toBe(before);});
it('unrelated profile changes, order and reload keep the same reminder dismissed',()=>{const s=dismissMissedReminder(fixture(),{persist:()=>true});s.profile.units='lb';s.program.days.reverse();const restored=deserializeState(serializeState(s));expect(missedReminderKey(restored)).toBe(s.dismissedMissedReminderKey);render(restored);expect(dismiss()).toBeNull();});
it('new missed occurrence reopens reminder',()=>{const s=dismissMissedReminder(fixture(),{persist:()=>true});vi.setSystemTime(new Date('2026-09-19T12:00:00'));render(s);expect(dismiss()).not.toBeNull();expect(document.body.textContent).toContain('3 missed workouts');});
it('resolved occurrence changes the key without changing other missed sessions',()=>{let s=dismissMissedReminder(fixture(),{persist:()=>true});const first=missedFlexibleSessions(s)[0];s=applyFlexibleWeek(s,proposeFlexibleWeek(s,{mode:'skip',sessionId:first.logicalSessionId})).state;render(s);expect(dismiss()).not.toBeNull();expect(document.body.textContent).toContain('MISSED WORKOUT');});
it('same count with a replaced occurrence still reopens reminder',()=>{let s=dismissMissedReminder(fixture(),{persist:()=>true});s=applyFlexibleWeek(s,proposeFlexibleWeek(s,{mode:'skip',sessionId:missedFlexibleSessions(s)[0].logicalSessionId})).state;vi.setSystemTime(new Date('2026-09-19T12:00:00'));expect(missedFlexibleSessions(s)).toHaveLength(2);render(s);expect(dismiss()).not.toBeNull();});
it('no missed occurrences shows no reminder; legacy or malformed preference is safe',()=>{const s=fixture();for(const item of missedFlexibleSessions(s))s.workouts.push({id:item.logicalSessionId,logicalSessionId:item.logicalSessionId,completedAt:'2026-09-18T12:00:00'});render(s);expect(dismiss()).toBeNull();const legacy=fixture();delete legacy.dismissedMissedReminderKey;expect(deserializeState(legacy).dismissedMissedReminderKey).toBeNull();legacy.dismissedMissedReminderKey={bad:true};expect(deserializeState(legacy).dismissedMissedReminderKey).toBeNull();});
