import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {blankState,buildProgram,serializeState,deserializeState} from './domain.js';
import {missedFlexibleSessions,flexibleSessions,proposeFlexibleWeek,applyFlexibleWeek} from './flexibleWeek.js';
import {skipMissedOccurrence,undoMissedSkip} from './missedWorkoutActions.js';
function fixture(){const s=blankState();Object.assign(s.profile,{goal:'Build muscle',experience:'Intermediate',daysPerWeek:3,availableDays:['Mon','Wed','Fri'],sessionMinutes:60,equipment:['full gym'],environment:'Commercial gym',priorities:['Balanced'],onboardingComplete:true});s.program=buildProgram(s.profile);s.program.trainingBlock.startDate='2026-09-14';s.program.createdAt='2026-09-14T12:00:00';return deserializeState(s);}
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-09-18T12:00:00'));});afterEach(()=>vi.useRealTimers());
it('skip and Undo preserve exact same-named occurrence, history and future plan; skipped fact survives reload',()=>{const s=fixture();s.program.days.forEach(d=>d.name='Same');const [a,b]=missedFlexibleSessions(s),before=structuredClone(s),persist=vi.fn(()=>true),r=skipMissedOccurrence(s,a.logicalSessionId,{persist});expect(persist).toHaveBeenCalledTimes(1);expect(s).toEqual(before);expect(r.state.workouts).toEqual(before.workouts);expect(r.state.program).toEqual(before.program);const reload=deserializeState(serializeState(r.state));expect(missedFlexibleSessions(reload).map(x=>x.logicalSessionId)).toEqual([b.logicalSessionId]);expect(flexibleSessions(reload).find(x=>x.logicalSessionId===a.logicalSessionId).status).toBe('skipped');const restored=undoMissedSkip(r.state,r.undo,{persist});expect(missedFlexibleSessions(restored).map(x=>x.logicalSessionId)).toEqual([a.logicalSessionId,b.logicalSessionId]);expect(restored.workouts).toEqual(before.workouts);});
it('uses the exact existing Flexible Week skip result',()=>{const s=fixture(),id=missedFlexibleSessions(s)[0].logicalSessionId;expect(skipMissedOccurrence(s,id,{persist:()=>true}).state).toEqual(applyFlexibleWeek(s,proposeFlexibleWeek(s,{mode:'skip',sessionId:id}),{adaptationChoice:'restore'}).state);});
it('failed writes never publish skip or undo and stale undo cannot replace new history',()=>{const s=fixture(),id=missedFlexibleSessions(s)[0].logicalSessionId,before=structuredClone(s);expect(()=>skipMissedOccurrence(s,id,{persist:()=>false})).toThrow(/still missed/);expect(s).toEqual(before);const r=skipMissedOccurrence(s,id,{persist:()=>true}),after=structuredClone(r.state);expect(()=>undoMissedSkip(r.state,r.undo,{persist:()=>false})).toThrow(/remains skipped/);expect(r.state).toEqual(after);r.state.workouts.push({id:'new',completedAt:'2026-09-18T12:00:00'});const write=vi.fn();expect(()=>undoMissedSkip(r.state,r.undo,{persist:write})).toThrow(/changed/);expect(write).not.toHaveBeenCalled();});
it.each(['active','completed','reserved','moved'])('rejects a no-longer actionable %s source',kind=>{let s=fixture();const a=missedFlexibleSessions(s)[0];if(kind==='active')s.activeWorkout={logicalSessionId:a.logicalSessionId};if(kind==='completed')s.workouts=[{id:'done',logicalSessionId:a.logicalSessionId,completedAt:'2026-09-14T12:00:00'}];if(kind==='reserved')s.todayAdaptation={programDayId:a.workoutId,date:a.scheduledDate,mode:'shorten'};if(kind==='moved')s=applyFlexibleWeek(s,proposeFlexibleWeek(s,{mode:'move',sessionId:a.logicalSessionId,toDate:'2026-09-19'})).state;expect(()=>skipMissedOccurrence(s,a.logicalSessionId,{persist:()=>true})).toThrow(/no longer/);});
