import {it,expect,vi} from 'vitest';
import {AIService} from './aiService.js';
const profile={goal:'Build muscle',experience:'Intermediate',daysPerWeek:2,availableDays:['Mon','Thu'],sessionMinutes:60,equipment:['full gym'],environment:'Commercial gym',priorities:['Balanced']};
const fixtures=[['A','Bench press\n3 x 8'],['B','Bench press\n3 sets\n8 reps'],['C','Bench press\n3 sets\n8-10 reps\n1 RIR'],['D','Chest\nBench press\n3 x 8\nChest fly\n4 x 12'],['E','Unknown cable thing\n3 x 15'],['F','Bench press\n3 sets\n4 sets'],['G','Y Balance Reach\n2 rounds'],['H','Optional:\nDips\nto failure']];
it.each(fixtures)('multiline fixture %s',async(id,text)=>{
 const net=vi.spyOn(globalThis,'fetch');const source='Monday\n'+text;const r=await AIService.importTrainingPlan(profile,source,{review:true});const ex=r.program.days.flatMap(d=>d.exercises),first=ex[0];expect(net).not.toHaveBeenCalled();net.mockRestore();expect(ex).toHaveLength(id==='D'?2:1);
 expect(r.program.importMetadata.sourceNotes.map(n=>n.text).join('\n')).toBe(source);
 if(['A','B','C','D'].includes(id)){expect(first.sets).toHaveLength(3);expect(first.repMin).toBe(8);expect(first.repMax).toBe(id==='C'?10:8);expect(first.targetRir).toBe(id==='C'?1:null);expect(first.sets.every(s=>s.weight===null)).toBe(true);}
 if(id==='D'){expect(ex[1].sets).toHaveLength(4);expect(ex[1].repMin).toBe(12);expect(ex.some(e=>e.originalImportedName==='Chest')).toBe(false);}
 if(id==='E'){expect(first.matchStatus).toBe('original');expect(first.originalImportedName).toBe('Unknown cable thing');expect(first.sets).toHaveLength(3);expect(first.repMin).toBe(15);expect(r.hybrid.needsAI).toBe(false);}
 if(id==='F'){expect(r.sourceReview.issues.some(i=>/Conflicting sets/.test(i.message)&&i.requiresSourceEdit)).toBe(true);expect(first.sets).toHaveLength(0);}
 if(id==='G'){expect(r.sourceReview.issues.some(i=>/Rounds/.test(i.message)&&i.requiresSourceEdit)).toBe(true);expect(first.sets).toHaveLength(0);}
 if(id==='H'){expect(first.hybridSource.optional).toBe(true);expect(first.failureTarget).toBe(true);expect(first.repMin).toBeNull();expect(r.sourceReview.issues.some(i=>i.field==='optional')).toBe(true);}
 expect(first.hybridSource.sourceSpan.text).toContain(id==='G'?'Y Balance Reach':'Bench press'===text.split('\n')[0]?'Bench press':id==='E'?'Unknown cable thing':id==='H'?'Dips':'Bench press');
});
it.each(['Bench press\n8 reps\n12 reps','Bench press\n3 x 8\n4 x 10'])('blocks incompatible facts instead of combining ranges: %s',async text=>{const r=await AIService.importTrainingPlan(profile,'Monday\n'+text,{review:true});expect(r.sourceReview.issues.some(i=>/Conflicting/.test(i.message))).toBe(true);});
it('handles bullets, indentation, blank lines and Slovenian notation with exact source',async()=>{const source='Ponedeljek\nPrsa\n  • Bench press\n    3 serije\n\n    8–10 ponovitev\n    1 RIR\n    počasi dol\n  • Unknown cable thing\n    4 x 12\n    full ROM';const r=await AIService.importTrainingPlan(profile,source,{review:true});const ex=r.program.days.flatMap(d=>d.exercises);expect(ex).toHaveLength(2);expect(ex[0].sets).toHaveLength(3);expect(ex[0].repMin).toBe(8);expect(ex[0].repMax).toBe(10);expect(ex[0].targetRir).toBe(1);expect(ex[0].hybridSource.sourceSpan.text).toBe(source.slice(source.indexOf('  • Bench'),source.indexOf('  • Unknown')-1));expect(ex[1].notes).toContain('full ROM');});
it('groups without a weekday and keeps ranges, instructions and supplied decimal load',async()=>{const r=await AIService.importTrainingPlan(profile,'Shoulder press\n3-4 sets\n8 reps\n12.5 kg\nslow eccentric\nfull ROM',{review:true});const e=r.program.days[0].exercises[0];expect(r.program.days.flatMap(d=>d.exercises)).toHaveLength(1);expect(e.notes).toContain('slow eccentric');expect(e.hybridSource.sourceSpan.text).toContain('full ROM');expect(r.sourceReview.issues.some(i=>i.exerciseId===e.id)).toBe(true);});
