import React,{act,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {SegmentedControl} from './SegmentedControl.jsx';
let root,host,changed;
beforeEach(()=>{globalThis.IS_REACT_ACT_ENVIRONMENT=true;host=document.createElement('div');document.body.append(host);root=createRoot(host);changed=vi.fn();});
afterEach(()=>{act(()=>root.unmount());host.remove();});
function mount(options=['CSV','JSON'],disabled=false){function Harness(){const[value,setValue]=useState(options[0]?.value??options[0]);return <SegmentedControl label="Format" options={options} value={value} disabled={disabled} onChange={v=>{changed(v);setValue(v);}}/>;}act(()=>root.render(<Harness/>));}
const radio=label=>[...host.querySelectorAll('[role="radio"]')].find(n=>n.textContent===label);
const click=label=>act(()=>radio(label).click());
const key=(label,value)=>act(()=>radio(label).dispatchEvent(new KeyboardEvent('keydown',{key:value,bubbles:true,cancelable:true})));
it('changes the controlled value synchronously, with one shared indicator and stationary labels',()=>{mount();click('JSON');expect(changed).toHaveBeenLastCalledWith('JSON');expect(radio('JSON').getAttribute('aria-checked')).toBe('true');expect(host.querySelector('[role="radiogroup"]').style.getPropertyValue('--rook-segment-index')).toBe('1');expect(host.querySelectorAll('.rook-segmented-indicator')).toHaveLength(1);expect([...host.querySelectorAll('button')].map(n=>n.textContent)).toEqual(['CSV','JSON']);});
it('rapid changes end on the last value and a repeated selected tap remains stable',()=>{mount();click('JSON');click('CSV');click('CSV');expect(radio('CSV').getAttribute('aria-checked')).toBe('true');expect(host.querySelector('[role="radiogroup"]').style.getPropertyValue('--rook-segment-index')).toBe('0');expect(changed.mock.calls).toEqual([['JSON'],['CSV'],['CSV']]);});
it('three/four-option keyboard navigation wraps, uses Home/End and skips disabled options',()=>{mount([{value:'system',label:'System'},{value:'light',label:'Light',disabled:true},{value:'dark',label:'Dark'},{value:'other',label:'Other'}]);key('System','ArrowRight');expect(document.activeElement).toBe(radio('Dark'));key('Dark','End');expect(document.activeElement).toBe(radio('Other'));key('Other','ArrowDown');expect(document.activeElement).toBe(radio('System'));key('System','ArrowLeft');expect(document.activeElement).toBe(radio('Other'));key('Other','Home');expect(radio('System').tabIndex).toBe(0);expect(radio('Light').disabled).toBe(true);expect(changed.mock.calls.flat()).not.toContain('light');});
it('a disabled group never changes selection or makes an enabled tab stop',()=>{mount(['CSV','JSON'],true);click('JSON');key('CSV','ArrowRight');expect(changed).not.toHaveBeenCalled();expect([...host.querySelectorAll('button')].every(n=>n.disabled&&n.tabIndex===-1)).toBe(true);});
it('pointer cancellation/scroll does not select or leave a press state, and unmount has no deferred action',()=>{mount();act(()=>{radio('JSON').dispatchEvent(new Event('pointerdown',{bubbles:true}));radio('JSON').dispatchEvent(new Event('pointercancel',{bubbles:true}));document.dispatchEvent(new Event('scroll'));});expect(changed).not.toHaveBeenCalled();expect(radio('CSV').getAttribute('aria-checked')).toBe('true');expect(host.querySelector('[data-row-pressed]')).toBeNull();click('JSON');act(()=>root.render(null));expect(changed).toHaveBeenCalledTimes(1);});
it('shared geometry, theme roles, keyboard focus and Reduced Motion are owned by one stylesheet',()=>{const css=readFileSync('src/segmentedControl.css','utf8');expect(css).toContain('min-height:44px');expect(css).toContain('white-space:normal');expect(css).toContain('var(--rook-surface)');expect(css).toContain('var(--rook-text)');expect(css).toContain(':focus-visible');expect(css).toMatch(/prefers-reduced-motion:[\s\S]*transition:none !important/);expect(css).not.toMatch(/#[0-9a-fA-F]{3,8}\b|background:\s*(white|black)/);});
