import React,{act,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {Stepper} from './App.jsx';
let root,host,changes;
beforeEach(()=>{globalThis.IS_REACT_ACT_ENVIRONMENT=true;host=document.createElement('div');document.body.append(host);root=createRoot(host);changes=vi.fn();});
afterEach(()=>{act(()=>root.unmount());host.remove();});
function mount(props={}){function Harness(){const[value,setValue]=useState(140);return <Stepper deferred required label="Weight for set 1" value={value} step={2.5} alignToStep {...props} onChange={v=>{changes(v);setValue(v);}}/>;}act(()=>root.render(<Harness/>));return{input:host.querySelector('input'),plus:host.querySelector('button:last-child'),minus:host.querySelector('button:first-child')};}
function type(input,value){act(()=>input.focus());act(()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));});}
it.each(['142.5','142,5'])('draft %s then plus commits exactly 145 and stale blur cannot restore it',raw=>{const{input,plus}=mount();type(input,raw);expect(changes).not.toHaveBeenCalled();act(()=>plus.click());expect(input.value).toBe('145');expect(changes).toHaveBeenCalledExactlyOnceWith(145);act(()=>input.blur());expect(changes).toHaveBeenCalledOnce();expect(input.value).toBe('145');});
it('comma decimal blur stores a canonical number once',()=>{const{input}=mount();type(input,'142,5');act(()=>input.blur());expect(changes).toHaveBeenCalledExactlyOnceWith(142.5);});
it('retains intermediate strings without writing and Enter uses blur commit',()=>{const{input}=mount();for(const raw of ['','1','12','12.','12.5','12,','12,5']){type(input,raw);expect(input.value).toBe(raw);}expect(changes).not.toHaveBeenCalled();act(()=>input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true})));expect(changes).toHaveBeenCalledExactlyOnceWith(12.5);});
it('required empty stays invalid through blur and refocus and blocks boundary commit',()=>{const{input}=mount();type(input,'');act(()=>input.blur());expect(input.value).toBe('');expect(input.getAttribute('aria-invalid')).toBe('true');let accepted;act(()=>{accepted=input.dispatchEvent(new Event('rook-commit-draft',{cancelable:true}));input.focus();});expect(accepted).toBe(false);expect(input.value).toBe('');expect(changes).not.toHaveBeenCalled();});
it('optional empty commits null, never zero',()=>{const{input}=mount({required:false});type(input,'');act(()=>input.blur());expect(changes).toHaveBeenCalledExactlyOnceWith(null);});
it('latest draft minus then 30 rapid increments has no lost or duplicated steps',()=>{const{input,minus,plus}=mount();type(input,'142.5');act(()=>minus.click());expect(input.value).toBe('140');act(()=>{for(let i=0;i<30;i++)plus.click();});expect(input.value).toBe('215');expect(changes).toHaveBeenCalledTimes(30);act(()=>input.blur());expect(changes).toHaveBeenCalledTimes(30);});
it('boundary commits are idempotent and leave text editing keys alone',()=>{const{input}=mount();type(input,'142.5');act(()=>{input.dispatchEvent(new Event('rook-commit-draft',{cancelable:true}));input.dispatchEvent(new Event('rook-commit-draft',{cancelable:true}));});expect(changes).toHaveBeenCalledExactlyOnceWith(142.5);const key=new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true,cancelable:true});act(()=>input.dispatchEvent(key));expect(key.defaultPrevented).toBe(false);expect(input.hasAttribute('role')).toBe(false);});
it('an explicit allowed per-side plus resolves empty to the existing first step',()=>{const{input,plus}=mount({value:null,step:1,min:1,integer:true,allowIncrementFromEmpty:true});expect(input.getAttribute('aria-invalid')).toBe('true');expect(plus.disabled).toBe(false);act(()=>plus.click());expect(changes).toHaveBeenCalledExactlyOnceWith(1);});
