import React, { act } from 'react';
import { createRoot } from 'react-dom/client';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { WorkoutPhotoCompare } from './WorkoutPhotoCompare.jsx';
import { canComparePhotos, chronologicalPhotoPair, toggleComparePhoto } from './workoutPhotoCompare.js';
import { getWorkoutPhoto } from './workoutPhotos.js';
vi.mock('./workoutPhotos.js', () => ({ getWorkoutPhoto: vi.fn() }));
let root, props, counter;
const entry=(id,day='2026-09-05')=>({id,day,workoutId:`workout-${id}`,workoutName:'Upper B',createdAt:`${day}T12:00:00Z`,metadataAvailable:true,workout:{id:`workout-${id}`,name:'Upper B'}});
const entries=[entry('new'),entry('old','2025-12-30'),entry('other','2026-08-01')];
const button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent===text);
async function render(overrides={}){
  props={entries,availability:Object.fromEntries(entries.map(e=>[e.id,true])),onAvailability:vi.fn(),onBack:vi.fn(),onClose:vi.fn(),onDeletePhoto:vi.fn().mockResolvedValue(true),onViewWorkout:vi.fn(),Header:({onBack,onClose})=><header><button onClick={onBack}>Back</button><button onClick={onClose}>Close</button></header>,Thumbnail:({entry,onOpen,disabled,selectionIndex})=><button disabled={disabled} aria-pressed={!!selectionIndex} onClick={onOpen}>{entry.id}</button>,Viewer:({photoUrl,onClose,onDelete})=><div role="dialog"><img src={photoUrl}/><button onClick={onClose}>Close viewer</button><button onClick={onDelete}>Delete</button></div>,...overrides};
  const host=document.createElement('div');document.body.append(host);root=createRoot(host);
  await act(async()=>root.render(<WorkoutPhotoCompare {...props}/>));
}
async function choose(){await act(async()=>{button('new').click();});await act(async()=>{button('old').click();});await act(async()=>button('COMPARE PHOTOS').click());}
beforeEach(()=>{globalThis.IS_REACT_ACT_ENVIRONMENT=true;counter=0;URL.createObjectURL=vi.fn(()=>`blob:test-${++counter}`);URL.revokeObjectURL=vi.fn();getWorkoutPhoto.mockReset().mockResolvedValue({blob:new Blob(['test'],{type:'image/jpeg'}),mimeType:'image/jpeg'});});
afterEach(()=>{act(()=>root?.unmount());root=null;document.body.innerHTML='';vi.restoreAllMocks();});

it('selection is unique, toggleable and capped at two',()=>{let selected=[];for(const e of entries)selected=toggleComparePhoto(selected,e);expect(selected.map(e=>e.id)).toEqual(['new','old']);expect(toggleComparePhoto(selected,entries[0])).toEqual([entries[1]]);expect(toggleComparePhoto([],{...entries[0],metadataAvailable:false})).toEqual([]);});
it('orders dates chronologically with deterministic same-date ties',()=>{const source=[entry('z'),entry('a'),entry('old','2025-01-01')];expect(chronologicalPhotoPair(source).map(e=>e.id)).toEqual(['old','a','z']);expect(source[0].id).toBe('z');});
for(const count of [0,1,2,300])it(`exactly two usable selections among ${count} entries`,()=>{const list=Array.from({length:count},(_,i)=>entry(String(i))),available=Object.fromEntries(list.map(e=>[e.id,true]));expect(canComparePhotos(list.slice(0,2),list,available)).toBe(count>=2);});
it('rejects corrupt, missing and duplicate selections',()=>{expect(canComparePhotos(entries.slice(0,2),entries,{new:true,old:false})).toBe(false);expect(canComparePhotos(entries.slice(0,2),entries.slice(0,1),{new:true,old:true})).toBe(false);expect(canComparePhotos([entries[0],entries[0]],entries,{new:true})).toBe(false);});
it('does not materialize full images while choosing',async()=>{await render();expect(getWorkoutPhoto).not.toHaveBeenCalled();expect(button('COMPARE PHOTOS').disabled).toBe(true);await act(async()=>button('new').click());expect(document.querySelector('h1').textContent).toBe('Choose another photo');expect(getWorkoutPhoto).not.toHaveBeenCalled();});
it('loads only the two selected originals and releases both on back',async()=>{await render();await choose();expect(getWorkoutPhoto).toHaveBeenCalledTimes(2);expect([...document.querySelectorAll('time')].map(e=>e.dateTime)).toEqual(['2025-12-30','2026-09-05']);await act(async()=>button('CHANGE PHOTOS').click());expect(URL.revokeObjectURL).toHaveBeenCalledTimes(2);expect(getWorkoutPhoto).toHaveBeenCalledTimes(2);});
it('reuses the selected original URL in the existing viewer',async()=>{await render();await choose();await act(async()=>document.querySelector('.photo-compare-inspect img').dispatchEvent(new Event('load')));await act(async()=>document.querySelector('.photo-compare-inspect').click());expect(document.querySelector('[role="dialog"]')).not.toBeNull();expect(getWorkoutPhoto).toHaveBeenCalledTimes(2);expect(URL.createObjectURL).toHaveBeenCalledTimes(2);});
it('failed deletion stays in the viewer and surfaces a retryable error',async()=>{await render({onDeletePhoto:vi.fn().mockResolvedValue(false),Viewer:({error,onDelete})=><div role="dialog"><p role="alert">{error}</p><button onClick={onDelete}>Delete</button></div>});await choose();await act(async()=>document.querySelector('.photo-compare-inspect img').dispatchEvent(new Event('load')));await act(async()=>document.querySelector('.photo-compare-inspect').click());await act(async()=>button('Delete').click());expect(document.querySelector('[role="dialog"] [role="alert"]').textContent).toContain('Try again');expect(URL.revokeObjectURL).not.toHaveBeenCalled();});
it('shows a missing image state and can keep the other selection',async()=>{getWorkoutPhoto.mockImplementation(id=>Promise.resolve(id==='old'?null:{blob:new Blob(['ok'],{type:'image/jpeg'})}));await render();await choose();expect(document.body.textContent).toContain('This photo is no longer available.');await act(async()=>button('Choose another').click());expect(document.querySelector('h1').textContent).toBe('Choose another photo');expect(button('new').getAttribute('aria-pressed')).toBe('true');});
it('handles decode corruption without displaying a broken comparison',async()=>{await render();await choose();await act(async()=>document.querySelector('.photo-compare-inspect img').dispatchEvent(new Event('error')));expect(document.querySelector('.photo-compare-unavailable')).not.toBeNull();expect(props.onAvailability).toHaveBeenCalledWith('old',false);});
it('rechecks a selected photo deleted from the live Timeline',async()=>{await render();await choose();await act(async()=>root.render(<WorkoutPhotoCompare {...props} entries={entries.filter(e=>e.id!=='old')}/>));expect(document.body.textContent).toContain('This photo is no longer available.');expect(URL.revokeObjectURL).toHaveBeenCalledTimes(2);});
it('rechecks external deletion on app focus',async()=>{await render();await choose();getWorkoutPhoto.mockResolvedValue(null);await act(async()=>window.dispatchEvent(new Event('focus')));expect(document.querySelectorAll('.photo-compare-unavailable')).toHaveLength(2);});
it('late reads after unmount create no object URLs',async()=>{let resolve;getWorkoutPhoto.mockReturnValue(new Promise(r=>resolve=r));await render();await choose();act(()=>root.unmount());root=null;await act(async()=>resolve({blob:new Blob(['late'],{type:'image/jpeg'})}));expect(URL.createObjectURL).not.toHaveBeenCalled();});
it('selection is ephemeral on remount and never mutates inputs',async()=>{const original=JSON.stringify(entries);await render();await choose();act(()=>root.unmount());root=null;await render();expect(document.querySelector('h1').textContent).toBe('Choose a photo');expect(JSON.stringify(entries)).toBe(original);});
