import {describe,it,expect} from 'vitest';
import {blankState,buildProgram,isoDay,weekDate,currentWeekSchedule,workoutPlanDate} from './domain.js';
import {calendarRange,monthDays,shiftMonth,calendarDayStates} from './workoutCalendar.js';
const fixture=()=>{const s=blankState();s.profile.availableDays=['Mon','Wed','Fri'];s.profile.daysPerWeek=3;s.program=buildProgram(s.profile);s.program.createdAt='2026-09-07T12:00:00Z';return s;};
describe('month date navigation',()=>{
 it('uses Monday-first complete rows including leap day',()=>{const days=monthDays('2024-02-15');expect(days.length%7).toBe(0);expect(new Date(`${days[0]}T12:00:00`).getDay()).toBe(1);expect(days).toContain('2024-02-29');expect(new Set(days).size).toBe(days.length);});
 it('moves across years and clamps January 31 to leap February',()=>{expect(shiftMonth('2024-01-31',1)).toBe('2024-02-29');expect(shiftMonth('2026-12-01',1)).toBe('2027-01-01');expect(shiftMonth('2026-01-01',-1)).toBe('2025-12-01');});
 it('preserves week-navigation bounds for a new user',()=>{expect(calendarRange(fixture(),'2026-09-07')).toEqual({min:'2026-09-07',max:'2026-09-13'});});
 it('includes recorded history and an explicitly scheduled future week',()=>{const s=fixture();s.workouts=[{completedAt:'2026-07-09T12:00:00Z',workoutDateKey:'2026-07-09'}];s.flexibleWeek={sessions:{a:{scheduledDate:'2026-10-06'}}};expect(calendarRange(s,'2026-09-07')).toEqual({min:'2026-07-06',max:'2026-10-11'});});
 it('retains precisely the existing weekly planned/completed semantics',()=>{const s=fixture();const date='2026-09-07',schedule=currentWeekSchedule(s,date);const planned=schedule[0];s.workouts=[{completedAt:date,workoutDateKey:planned.scheduledDate,programDayId:planned.workout.id}];s.activeWorkout={workoutDateKey:schedule[1].scheduledDate};const before=JSON.stringify(s),days=monthDays(date),states=calendarDayStates(s,days);for(const key of days){const week=currentWeekSchedule(s,key),workout=week.find(w=>w.scheduledDate===key)?.workout;expect(states[key].complete).toBe(s.workouts.some(w=>workoutPlanDate(w)===key&&(!workout||w.programDayId===workout.id||(!w.programDayId&&w.templateId===workout.weekday))));expect(states[key].planned).toBe(Boolean(workout));}expect(states[schedule[1].scheduledDate].active).toBe(true);expect(JSON.stringify(s)).toBe(before);});
 it('follows moved sessions, without marking their original day as planned',()=>{const s=fixture(),key=isoDay(weekDate('Mon','2026-09-07')),day=s.program.days[0];s.weekScheduleOverrides={[key]:{[day.id]:'2026-09-08'}};const states=calendarDayStates(s,monthDays(key));expect(states['2026-09-08'].planned).toBe(true);expect(states['2026-09-07'].planned).toBe(false);});
});
